/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutUserroleDao extends org.jooq.impl.DAOImpl<org.tylproject.db.public_.tables.records.AutUserroleRecord, org.tylproject.db.public_.tables.pojos.AutUserrole, java.lang.String> {

	/**
	 * Create a new AutUserroleDao without any configuration
	 */
	public AutUserroleDao() {
		super(org.tylproject.db.public_.tables.AutUserrole.AUT_USERROLE, org.tylproject.db.public_.tables.pojos.AutUserrole.class);
	}

	/**
	 * Create a new AutUserroleDao with an attached configuration
	 */
	public AutUserroleDao(org.jooq.Configuration configuration) {
		super(org.tylproject.db.public_.tables.AutUserrole.AUT_USERROLE, org.tylproject.db.public_.tables.pojos.AutUserrole.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.String getId(org.tylproject.db.public_.tables.pojos.AutUserrole object) {
		return object.getIdAutUserrole();
	}

	/**
	 * Fetch records that have <code>id_aut_userrole IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.AutUserrole> fetchByIdAutUserrole(java.lang.String... values) {
		return fetch(org.tylproject.db.public_.tables.AutUserrole.AUT_USERROLE.ID_AUT_USERROLE, values);
	}

	/**
	 * Fetch a unique record that has <code>id_aut_userrole = value</code>
	 */
	public org.tylproject.db.public_.tables.pojos.AutUserrole fetchOneByIdAutUserrole(java.lang.String value) {
		return fetchOne(org.tylproject.db.public_.tables.AutUserrole.AUT_USERROLE.ID_AUT_USERROLE, value);
	}

	/**
	 * Fetch records that have <code>canceled IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.AutUserrole> fetchByCanceled(java.lang.Boolean... values) {
		return fetch(org.tylproject.db.public_.tables.AutUserrole.AUT_USERROLE.CANCELED, values);
	}

	/**
	 * Fetch records that have <code>version IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.AutUserrole> fetchByVersion(java.lang.Integer... values) {
		return fetch(org.tylproject.db.public_.tables.AutUserrole.AUT_USERROLE.VERSION, values);
	}

	/**
	 * Fetch records that have <code>track IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.AutUserrole> fetchByTrack(org.tylproject.db.public_.udt.records.TrackRecord... values) {
		return fetch(org.tylproject.db.public_.tables.AutUserrole.AUT_USERROLE.TRACK, values);
	}
}
