/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BasDistrictDao extends org.jooq.impl.DAOImpl<org.tylproject.db.public_.tables.records.BasDistrictRecord, org.tylproject.db.public_.tables.pojos.BasDistrict, java.lang.Integer> {

	/**
	 * Create a new BasDistrictDao without any configuration
	 */
	public BasDistrictDao() {
		super(org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT, org.tylproject.db.public_.tables.pojos.BasDistrict.class);
	}

	/**
	 * Create a new BasDistrictDao with an attached configuration
	 */
	public BasDistrictDao(org.jooq.Configuration configuration) {
		super(org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT, org.tylproject.db.public_.tables.pojos.BasDistrict.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(org.tylproject.db.public_.tables.pojos.BasDistrict object) {
		return object.getIdBasDistrict();
	}

	/**
	 * Fetch records that have <code>id_bas_district IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.BasDistrict> fetchByIdBasDistrict(java.lang.Integer... values) {
		return fetch(org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT.ID_BAS_DISTRICT, values);
	}

	/**
	 * Fetch a unique record that has <code>id_bas_district = value</code>
	 */
	public org.tylproject.db.public_.tables.pojos.BasDistrict fetchOneByIdBasDistrict(java.lang.Integer value) {
		return fetchOne(org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT.ID_BAS_DISTRICT, value);
	}

	/**
	 * Fetch records that have <code>id_bas_country IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.BasDistrict> fetchByIdBasCountry(java.lang.String... values) {
		return fetch(org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT.ID_BAS_COUNTRY, values);
	}

	/**
	 * Fetch records that have <code>district IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.BasDistrict> fetchByDistrict(java.lang.String... values) {
		return fetch(org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT.DISTRICT, values);
	}

	/**
	 * Fetch records that have <code>city_name IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.BasDistrict> fetchByCityName(java.lang.String... values) {
		return fetch(org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT.CITY_NAME, values);
	}

	/**
	 * Fetch records that have <code>postal_code IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.BasDistrict> fetchByPostalCode(java.lang.String... values) {
		return fetch(org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT.POSTAL_CODE, values);
	}

	/**
	 * Fetch records that have <code>canceled IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.BasDistrict> fetchByCanceled(java.lang.Boolean... values) {
		return fetch(org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT.CANCELED, values);
	}

	/**
	 * Fetch records that have <code>version IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.BasDistrict> fetchByVersion(java.lang.Integer... values) {
		return fetch(org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT.VERSION, values);
	}

	/**
	 * Fetch records that have <code>track IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.BasDistrict> fetchByTrack(org.tylproject.db.public_.udt.records.TrackRecord... values) {
		return fetch(org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT.TRACK, values);
	}
}
