/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BasLanguageDao extends org.jooq.impl.DAOImpl<org.tylproject.db.public_.tables.records.BasLanguageRecord, org.tylproject.db.public_.tables.pojos.BasLanguage, java.lang.String> {

	/**
	 * Create a new BasLanguageDao without any configuration
	 */
	public BasLanguageDao() {
		super(org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE, org.tylproject.db.public_.tables.pojos.BasLanguage.class);
	}

	/**
	 * Create a new BasLanguageDao with an attached configuration
	 */
	public BasLanguageDao(org.jooq.Configuration configuration) {
		super(org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE, org.tylproject.db.public_.tables.pojos.BasLanguage.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.String getId(org.tylproject.db.public_.tables.pojos.BasLanguage object) {
		return object.getIdBasLanguage();
	}

	/**
	 * Fetch records that have <code>id_bas_language IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.BasLanguage> fetchByIdBasLanguage(java.lang.String... values) {
		return fetch(org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.ID_BAS_LANGUAGE, values);
	}

	/**
	 * Fetch a unique record that has <code>id_bas_language = value</code>
	 */
	public org.tylproject.db.public_.tables.pojos.BasLanguage fetchOneByIdBasLanguage(java.lang.String value) {
		return fetchOne(org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.ID_BAS_LANGUAGE, value);
	}

	/**
	 * Fetch records that have <code>flag IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.BasLanguage> fetchByFlag(java.lang.String... values) {
		return fetch(org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.FLAG, values);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.BasLanguage> fetchByName(java.lang.String... values) {
		return fetch(org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.NAME, values);
	}

	/**
	 * Fetch records that have <code>created_on IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.BasLanguage> fetchByCreatedOn(java.sql.Timestamp... values) {
		return fetch(org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.CREATED_ON, values);
	}

	/**
	 * Fetch records that have <code>created_by IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.BasLanguage> fetchByCreatedBy(java.lang.String... values) {
		return fetch(org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.CREATED_BY, values);
	}

	/**
	 * Fetch records that have <code>updated_on IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.BasLanguage> fetchByUpdatedOn(java.sql.Timestamp... values) {
		return fetch(org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.UPDATED_ON, values);
	}

	/**
	 * Fetch records that have <code>updated_by IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.BasLanguage> fetchByUpdatedBy(java.lang.String... values) {
		return fetch(org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.UPDATED_BY, values);
	}

	/**
	 * Fetch records that have <code>canceled IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.BasLanguage> fetchByCanceled(java.lang.Boolean... values) {
		return fetch(org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.CANCELED, values);
	}

	/**
	 * Fetch records that have <code>version IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.BasLanguage> fetchByVersion(java.lang.Integer... values) {
		return fetch(org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.VERSION, values);
	}

	/**
	 * Fetch records that have <code>active IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.BasLanguage> fetchByActive(java.lang.Boolean... values) {
		return fetch(org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.ACTIVE, values);
	}
}
