/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExcExchangerateDao extends org.jooq.impl.DAOImpl<org.tylproject.db.public_.tables.records.ExcExchangerateRecord, org.tylproject.db.public_.tables.pojos.ExcExchangerate, java.lang.Integer> {

	/**
	 * Create a new ExcExchangerateDao without any configuration
	 */
	public ExcExchangerateDao() {
		super(org.tylproject.db.public_.tables.ExcExchangerate.EXC_EXCHANGERATE, org.tylproject.db.public_.tables.pojos.ExcExchangerate.class);
	}

	/**
	 * Create a new ExcExchangerateDao with an attached configuration
	 */
	public ExcExchangerateDao(org.jooq.Configuration configuration) {
		super(org.tylproject.db.public_.tables.ExcExchangerate.EXC_EXCHANGERATE, org.tylproject.db.public_.tables.pojos.ExcExchangerate.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(org.tylproject.db.public_.tables.pojos.ExcExchangerate object) {
		return object.getIdExcExchangerate();
	}

	/**
	 * Fetch records that have <code>id_exc_exchangerate IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.ExcExchangerate> fetchByIdExcExchangerate(java.lang.Integer... values) {
		return fetch(org.tylproject.db.public_.tables.ExcExchangerate.EXC_EXCHANGERATE.ID_EXC_EXCHANGERATE, values);
	}

	/**
	 * Fetch a unique record that has <code>id_exc_exchangerate = value</code>
	 */
	public org.tylproject.db.public_.tables.pojos.ExcExchangerate fetchOneByIdExcExchangerate(java.lang.Integer value) {
		return fetchOne(org.tylproject.db.public_.tables.ExcExchangerate.EXC_EXCHANGERATE.ID_EXC_EXCHANGERATE, value);
	}
}
