/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TodosDao extends org.jooq.impl.DAOImpl<org.tylproject.db.public_.tables.records.TodosRecord, org.tylproject.db.public_.tables.pojos.Todos, java.lang.Integer> {

	/**
	 * Create a new TodosDao without any configuration
	 */
	public TodosDao() {
		super(org.tylproject.db.public_.tables.Todos.TODOS, org.tylproject.db.public_.tables.pojos.Todos.class);
	}

	/**
	 * Create a new TodosDao with an attached configuration
	 */
	public TodosDao(org.jooq.Configuration configuration) {
		super(org.tylproject.db.public_.tables.Todos.TODOS, org.tylproject.db.public_.tables.pojos.Todos.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(org.tylproject.db.public_.tables.pojos.Todos object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.Todos> fetchById(java.lang.Integer... values) {
		return fetch(org.tylproject.db.public_.tables.Todos.TODOS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.tylproject.db.public_.tables.pojos.Todos fetchOneById(java.lang.Integer value) {
		return fetchOne(org.tylproject.db.public_.tables.Todos.TODOS.ID, value);
	}

	/**
	 * Fetch records that have <code>creation_time IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.Todos> fetchByCreationTime(java.sql.Timestamp... values) {
		return fetch(org.tylproject.db.public_.tables.Todos.TODOS.CREATION_TIME, values);
	}

	/**
	 * Fetch records that have <code>description IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.Todos> fetchByDescription(java.lang.String... values) {
		return fetch(org.tylproject.db.public_.tables.Todos.TODOS.DESCRIPTION, values);
	}

	/**
	 * Fetch records that have <code>modification_time IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.Todos> fetchByModificationTime(java.sql.Timestamp... values) {
		return fetch(org.tylproject.db.public_.tables.Todos.TODOS.MODIFICATION_TIME, values);
	}

	/**
	 * Fetch records that have <code>title IN (values)</code>
	 */
	public java.util.List<org.tylproject.db.public_.tables.pojos.Todos> fetchByTitle(java.lang.String... values) {
		return fetch(org.tylproject.db.public_.tables.Todos.TODOS.TITLE, values);
	}
}
