/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutCompany implements java.io.Serializable {

	private static final long serialVersionUID = 788682689;

	private java.lang.String                          idAutCompany;
	private java.lang.String                          name;
	private java.lang.Integer                         idParParty;
	private java.lang.Boolean                         canceled;
	private java.lang.Integer                         version;
	private org.tylproject.db.public_.udt.pojos.Track track;

	public AutCompany() {}

	public AutCompany(
		java.lang.String                          idAutCompany,
		java.lang.String                          name,
		java.lang.Integer                         idParParty,
		java.lang.Boolean                         canceled,
		java.lang.Integer                         version,
		org.tylproject.db.public_.udt.pojos.Track track
	) {
		this.idAutCompany = idAutCompany;
		this.name = name;
		this.idParParty = idParParty;
		this.canceled = canceled;
		this.version = version;
		this.track = track;
	}

	public java.lang.String getIdAutCompany() {
		return this.idAutCompany;
	}

	public AutCompany setIdAutCompany(java.lang.String idAutCompany) {
		this.idAutCompany = idAutCompany;
		return this;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public AutCompany setName(java.lang.String name) {
		this.name = name;
		return this;
	}

	public java.lang.Integer getIdParParty() {
		return this.idParParty;
	}

	public AutCompany setIdParParty(java.lang.Integer idParParty) {
		this.idParParty = idParParty;
		return this;
	}

	public java.lang.Boolean getCanceled() {
		return this.canceled;
	}

	public AutCompany setCanceled(java.lang.Boolean canceled) {
		this.canceled = canceled;
		return this;
	}

	public java.lang.Integer getVersion() {
		return this.version;
	}

	public AutCompany setVersion(java.lang.Integer version) {
		this.version = version;
		return this;
	}

	public org.tylproject.db.public_.udt.pojos.Track getTrack() {
		return this.track;
	}

	public AutCompany setTrack(org.tylproject.db.public_.udt.pojos.Track track) {
		this.track = track;
		return this;
	}
}
