/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutUserrole implements java.io.Serializable {

	private static final long serialVersionUID = -554631559;

	private java.lang.String                          idAutUserrole;
	private java.lang.Boolean                         canceled;
	private java.lang.Integer                         version;
	private org.tylproject.db.public_.udt.pojos.Track track;

	public AutUserrole() {}

	public AutUserrole(
		java.lang.String                          idAutUserrole,
		java.lang.Boolean                         canceled,
		java.lang.Integer                         version,
		org.tylproject.db.public_.udt.pojos.Track track
	) {
		this.idAutUserrole = idAutUserrole;
		this.canceled = canceled;
		this.version = version;
		this.track = track;
	}

	public java.lang.String getIdAutUserrole() {
		return this.idAutUserrole;
	}

	public AutUserrole setIdAutUserrole(java.lang.String idAutUserrole) {
		this.idAutUserrole = idAutUserrole;
		return this;
	}

	public java.lang.Boolean getCanceled() {
		return this.canceled;
	}

	public AutUserrole setCanceled(java.lang.Boolean canceled) {
		this.canceled = canceled;
		return this;
	}

	public java.lang.Integer getVersion() {
		return this.version;
	}

	public AutUserrole setVersion(java.lang.Integer version) {
		this.version = version;
		return this;
	}

	public org.tylproject.db.public_.udt.pojos.Track getTrack() {
		return this.track;
	}

	public AutUserrole setTrack(org.tylproject.db.public_.udt.pojos.Track track) {
		this.track = track;
		return this;
	}
}
