/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutUserroleCompany implements java.io.Serializable {

	private static final long serialVersionUID = -667515204;

	private java.lang.Integer                         idAutUserroleCompany;
	private java.lang.String                          idAutUser;
	private java.lang.String                          idAutUserrole;
	private java.lang.String                          idAutCompany;
	private java.lang.Integer                         version;
	private org.tylproject.db.public_.udt.pojos.Track track;

	public AutUserroleCompany() {}

	public AutUserroleCompany(
		java.lang.Integer                         idAutUserroleCompany,
		java.lang.String                          idAutUser,
		java.lang.String                          idAutUserrole,
		java.lang.String                          idAutCompany,
		java.lang.Integer                         version,
		org.tylproject.db.public_.udt.pojos.Track track
	) {
		this.idAutUserroleCompany = idAutUserroleCompany;
		this.idAutUser = idAutUser;
		this.idAutUserrole = idAutUserrole;
		this.idAutCompany = idAutCompany;
		this.version = version;
		this.track = track;
	}

	public java.lang.Integer getIdAutUserroleCompany() {
		return this.idAutUserroleCompany;
	}

	public AutUserroleCompany setIdAutUserroleCompany(java.lang.Integer idAutUserroleCompany) {
		this.idAutUserroleCompany = idAutUserroleCompany;
		return this;
	}

	public java.lang.String getIdAutUser() {
		return this.idAutUser;
	}

	public AutUserroleCompany setIdAutUser(java.lang.String idAutUser) {
		this.idAutUser = idAutUser;
		return this;
	}

	public java.lang.String getIdAutUserrole() {
		return this.idAutUserrole;
	}

	public AutUserroleCompany setIdAutUserrole(java.lang.String idAutUserrole) {
		this.idAutUserrole = idAutUserrole;
		return this;
	}

	public java.lang.String getIdAutCompany() {
		return this.idAutCompany;
	}

	public AutUserroleCompany setIdAutCompany(java.lang.String idAutCompany) {
		this.idAutCompany = idAutCompany;
		return this;
	}

	public java.lang.Integer getVersion() {
		return this.version;
	}

	public AutUserroleCompany setVersion(java.lang.Integer version) {
		this.version = version;
		return this;
	}

	public org.tylproject.db.public_.udt.pojos.Track getTrack() {
		return this.track;
	}

	public AutUserroleCompany setTrack(org.tylproject.db.public_.udt.pojos.Track track) {
		this.track = track;
		return this;
	}
}
