/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutUserroleCompany implements java.io.Serializable {

	private static final long serialVersionUID = 247930625;

	private java.lang.Integer  idAutUserroleCompany;
	private java.lang.String   idAutUser;
	private java.lang.String   idAutUserrole;
	private java.lang.String   idAutCompany;
	private java.sql.Timestamp createdOn;
	private java.lang.String   createdBy;
	private java.sql.Timestamp updatedOn;
	private java.lang.String   updatedBy;
	private java.lang.Integer  version;

	public AutUserroleCompany() {}

	public AutUserroleCompany(
		java.lang.Integer  idAutUserroleCompany,
		java.lang.String   idAutUser,
		java.lang.String   idAutUserrole,
		java.lang.String   idAutCompany,
		java.sql.Timestamp createdOn,
		java.lang.String   createdBy,
		java.sql.Timestamp updatedOn,
		java.lang.String   updatedBy,
		java.lang.Integer  version
	) {
		this.idAutUserroleCompany = idAutUserroleCompany;
		this.idAutUser = idAutUser;
		this.idAutUserrole = idAutUserrole;
		this.idAutCompany = idAutCompany;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.updatedOn = updatedOn;
		this.updatedBy = updatedBy;
		this.version = version;
	}

	public java.lang.Integer getIdAutUserroleCompany() {
		return this.idAutUserroleCompany;
	}

	public AutUserroleCompany setIdAutUserroleCompany(java.lang.Integer idAutUserroleCompany) {
		this.idAutUserroleCompany = idAutUserroleCompany;
		return this;
	}

	public java.lang.String getIdAutUser() {
		return this.idAutUser;
	}

	public AutUserroleCompany setIdAutUser(java.lang.String idAutUser) {
		this.idAutUser = idAutUser;
		return this;
	}

	public java.lang.String getIdAutUserrole() {
		return this.idAutUserrole;
	}

	public AutUserroleCompany setIdAutUserrole(java.lang.String idAutUserrole) {
		this.idAutUserrole = idAutUserrole;
		return this;
	}

	public java.lang.String getIdAutCompany() {
		return this.idAutCompany;
	}

	public AutUserroleCompany setIdAutCompany(java.lang.String idAutCompany) {
		this.idAutCompany = idAutCompany;
		return this;
	}

	public java.sql.Timestamp getCreatedOn() {
		return this.createdOn;
	}

	public AutUserroleCompany setCreatedOn(java.sql.Timestamp createdOn) {
		this.createdOn = createdOn;
		return this;
	}

	public java.lang.String getCreatedBy() {
		return this.createdBy;
	}

	public AutUserroleCompany setCreatedBy(java.lang.String createdBy) {
		this.createdBy = createdBy;
		return this;
	}

	public java.sql.Timestamp getUpdatedOn() {
		return this.updatedOn;
	}

	public AutUserroleCompany setUpdatedOn(java.sql.Timestamp updatedOn) {
		this.updatedOn = updatedOn;
		return this;
	}

	public java.lang.String getUpdatedBy() {
		return this.updatedBy;
	}

	public AutUserroleCompany setUpdatedBy(java.lang.String updatedBy) {
		this.updatedBy = updatedBy;
		return this;
	}

	public java.lang.Integer getVersion() {
		return this.version;
	}

	public AutUserroleCompany setVersion(java.lang.Integer version) {
		this.version = version;
		return this;
	}
}
