/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BasCountry implements java.io.Serializable {

	private static final long serialVersionUID = -1524089640;

	private java.lang.String   idBasCountry;
	private java.lang.String   officialName;
	private java.lang.String   twoCharsCode;
	private java.lang.Integer  numericCode;
	private java.sql.Timestamp createdOn;
	private java.lang.String   createdBy;
	private java.sql.Timestamp updatedOn;
	private java.lang.String   updatedBy;
	private java.lang.Boolean  canceled;
	private java.lang.Integer  version;

	public BasCountry() {}

	public BasCountry(
		java.lang.String   idBasCountry,
		java.lang.String   officialName,
		java.lang.String   twoCharsCode,
		java.lang.Integer  numericCode,
		java.sql.Timestamp createdOn,
		java.lang.String   createdBy,
		java.sql.Timestamp updatedOn,
		java.lang.String   updatedBy,
		java.lang.Boolean  canceled,
		java.lang.Integer  version
	) {
		this.idBasCountry = idBasCountry;
		this.officialName = officialName;
		this.twoCharsCode = twoCharsCode;
		this.numericCode = numericCode;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.updatedOn = updatedOn;
		this.updatedBy = updatedBy;
		this.canceled = canceled;
		this.version = version;
	}

	public java.lang.String getIdBasCountry() {
		return this.idBasCountry;
	}

	public BasCountry setIdBasCountry(java.lang.String idBasCountry) {
		this.idBasCountry = idBasCountry;
		return this;
	}

	public java.lang.String getOfficialName() {
		return this.officialName;
	}

	public BasCountry setOfficialName(java.lang.String officialName) {
		this.officialName = officialName;
		return this;
	}

	public java.lang.String getTwoCharsCode() {
		return this.twoCharsCode;
	}

	public BasCountry setTwoCharsCode(java.lang.String twoCharsCode) {
		this.twoCharsCode = twoCharsCode;
		return this;
	}

	public java.lang.Integer getNumericCode() {
		return this.numericCode;
	}

	public BasCountry setNumericCode(java.lang.Integer numericCode) {
		this.numericCode = numericCode;
		return this;
	}

	public java.sql.Timestamp getCreatedOn() {
		return this.createdOn;
	}

	public BasCountry setCreatedOn(java.sql.Timestamp createdOn) {
		this.createdOn = createdOn;
		return this;
	}

	public java.lang.String getCreatedBy() {
		return this.createdBy;
	}

	public BasCountry setCreatedBy(java.lang.String createdBy) {
		this.createdBy = createdBy;
		return this;
	}

	public java.sql.Timestamp getUpdatedOn() {
		return this.updatedOn;
	}

	public BasCountry setUpdatedOn(java.sql.Timestamp updatedOn) {
		this.updatedOn = updatedOn;
		return this;
	}

	public java.lang.String getUpdatedBy() {
		return this.updatedBy;
	}

	public BasCountry setUpdatedBy(java.lang.String updatedBy) {
		this.updatedBy = updatedBy;
		return this;
	}

	public java.lang.Boolean getCanceled() {
		return this.canceled;
	}

	public BasCountry setCanceled(java.lang.Boolean canceled) {
		this.canceled = canceled;
		return this;
	}

	public java.lang.Integer getVersion() {
		return this.version;
	}

	public BasCountry setVersion(java.lang.Integer version) {
		this.version = version;
		return this;
	}
}
