/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BasCountry implements java.io.Serializable {

	private static final long serialVersionUID = 1322613407;

	private java.lang.String                          idBasCountry;
	private java.lang.String                          officialName;
	private java.lang.String                          twoCharsCode;
	private java.lang.Integer                         numericCode;
	private java.lang.Boolean                         canceled;
	private java.lang.Integer                         version;
	private org.tylproject.db.public_.udt.pojos.Track track;

	public BasCountry() {}

	public BasCountry(
		java.lang.String                          idBasCountry,
		java.lang.String                          officialName,
		java.lang.String                          twoCharsCode,
		java.lang.Integer                         numericCode,
		java.lang.Boolean                         canceled,
		java.lang.Integer                         version,
		org.tylproject.db.public_.udt.pojos.Track track
	) {
		this.idBasCountry = idBasCountry;
		this.officialName = officialName;
		this.twoCharsCode = twoCharsCode;
		this.numericCode = numericCode;
		this.canceled = canceled;
		this.version = version;
		this.track = track;
	}

	public java.lang.String getIdBasCountry() {
		return this.idBasCountry;
	}

	public BasCountry setIdBasCountry(java.lang.String idBasCountry) {
		this.idBasCountry = idBasCountry;
		return this;
	}

	public java.lang.String getOfficialName() {
		return this.officialName;
	}

	public BasCountry setOfficialName(java.lang.String officialName) {
		this.officialName = officialName;
		return this;
	}

	public java.lang.String getTwoCharsCode() {
		return this.twoCharsCode;
	}

	public BasCountry setTwoCharsCode(java.lang.String twoCharsCode) {
		this.twoCharsCode = twoCharsCode;
		return this;
	}

	public java.lang.Integer getNumericCode() {
		return this.numericCode;
	}

	public BasCountry setNumericCode(java.lang.Integer numericCode) {
		this.numericCode = numericCode;
		return this;
	}

	public java.lang.Boolean getCanceled() {
		return this.canceled;
	}

	public BasCountry setCanceled(java.lang.Boolean canceled) {
		this.canceled = canceled;
		return this;
	}

	public java.lang.Integer getVersion() {
		return this.version;
	}

	public BasCountry setVersion(java.lang.Integer version) {
		this.version = version;
		return this;
	}

	public org.tylproject.db.public_.udt.pojos.Track getTrack() {
		return this.track;
	}

	public BasCountry setTrack(org.tylproject.db.public_.udt.pojos.Track track) {
		this.track = track;
		return this;
	}
}
