/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BasDistrict implements java.io.Serializable {

	private static final long serialVersionUID = 61259149;

	private java.lang.Integer  idBasDistrict;
	private java.lang.String   idBasCountry;
	private java.lang.String   district;
	private java.lang.String   cityName;
	private java.lang.String   postalCode;
	private java.sql.Timestamp createdOn;
	private java.lang.String   createdBy;
	private java.sql.Timestamp updatedOn;
	private java.lang.String   updatedBy;
	private java.lang.Boolean  canceled;
	private java.lang.Integer  version;

	public BasDistrict() {}

	public BasDistrict(
		java.lang.Integer  idBasDistrict,
		java.lang.String   idBasCountry,
		java.lang.String   district,
		java.lang.String   cityName,
		java.lang.String   postalCode,
		java.sql.Timestamp createdOn,
		java.lang.String   createdBy,
		java.sql.Timestamp updatedOn,
		java.lang.String   updatedBy,
		java.lang.Boolean  canceled,
		java.lang.Integer  version
	) {
		this.idBasDistrict = idBasDistrict;
		this.idBasCountry = idBasCountry;
		this.district = district;
		this.cityName = cityName;
		this.postalCode = postalCode;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.updatedOn = updatedOn;
		this.updatedBy = updatedBy;
		this.canceled = canceled;
		this.version = version;
	}

	public java.lang.Integer getIdBasDistrict() {
		return this.idBasDistrict;
	}

	public BasDistrict setIdBasDistrict(java.lang.Integer idBasDistrict) {
		this.idBasDistrict = idBasDistrict;
		return this;
	}

	public java.lang.String getIdBasCountry() {
		return this.idBasCountry;
	}

	public BasDistrict setIdBasCountry(java.lang.String idBasCountry) {
		this.idBasCountry = idBasCountry;
		return this;
	}

	public java.lang.String getDistrict() {
		return this.district;
	}

	public BasDistrict setDistrict(java.lang.String district) {
		this.district = district;
		return this;
	}

	public java.lang.String getCityName() {
		return this.cityName;
	}

	public BasDistrict setCityName(java.lang.String cityName) {
		this.cityName = cityName;
		return this;
	}

	public java.lang.String getPostalCode() {
		return this.postalCode;
	}

	public BasDistrict setPostalCode(java.lang.String postalCode) {
		this.postalCode = postalCode;
		return this;
	}

	public java.sql.Timestamp getCreatedOn() {
		return this.createdOn;
	}

	public BasDistrict setCreatedOn(java.sql.Timestamp createdOn) {
		this.createdOn = createdOn;
		return this;
	}

	public java.lang.String getCreatedBy() {
		return this.createdBy;
	}

	public BasDistrict setCreatedBy(java.lang.String createdBy) {
		this.createdBy = createdBy;
		return this;
	}

	public java.sql.Timestamp getUpdatedOn() {
		return this.updatedOn;
	}

	public BasDistrict setUpdatedOn(java.sql.Timestamp updatedOn) {
		this.updatedOn = updatedOn;
		return this;
	}

	public java.lang.String getUpdatedBy() {
		return this.updatedBy;
	}

	public BasDistrict setUpdatedBy(java.lang.String updatedBy) {
		this.updatedBy = updatedBy;
		return this;
	}

	public java.lang.Boolean getCanceled() {
		return this.canceled;
	}

	public BasDistrict setCanceled(java.lang.Boolean canceled) {
		this.canceled = canceled;
		return this;
	}

	public java.lang.Integer getVersion() {
		return this.version;
	}

	public BasDistrict setVersion(java.lang.Integer version) {
		this.version = version;
		return this;
	}
}
