/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BasFreezereason implements java.io.Serializable {

	private static final long serialVersionUID = 1241348907;

	private java.lang.String                          idFreezereason;
	private java.lang.String                          discriminator;
	private java.lang.String                          description;
	private java.lang.Boolean                         canceled;
	private java.lang.Integer                         version;
	private org.tylproject.db.public_.udt.pojos.Track track;

	public BasFreezereason() {}

	public BasFreezereason(
		java.lang.String                          idFreezereason,
		java.lang.String                          discriminator,
		java.lang.String                          description,
		java.lang.Boolean                         canceled,
		java.lang.Integer                         version,
		org.tylproject.db.public_.udt.pojos.Track track
	) {
		this.idFreezereason = idFreezereason;
		this.discriminator = discriminator;
		this.description = description;
		this.canceled = canceled;
		this.version = version;
		this.track = track;
	}

	public java.lang.String getIdFreezereason() {
		return this.idFreezereason;
	}

	public BasFreezereason setIdFreezereason(java.lang.String idFreezereason) {
		this.idFreezereason = idFreezereason;
		return this;
	}

	public java.lang.String getDiscriminator() {
		return this.discriminator;
	}

	public BasFreezereason setDiscriminator(java.lang.String discriminator) {
		this.discriminator = discriminator;
		return this;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public BasFreezereason setDescription(java.lang.String description) {
		this.description = description;
		return this;
	}

	public java.lang.Boolean getCanceled() {
		return this.canceled;
	}

	public BasFreezereason setCanceled(java.lang.Boolean canceled) {
		this.canceled = canceled;
		return this;
	}

	public java.lang.Integer getVersion() {
		return this.version;
	}

	public BasFreezereason setVersion(java.lang.Integer version) {
		this.version = version;
		return this;
	}

	public org.tylproject.db.public_.udt.pojos.Track getTrack() {
		return this.track;
	}

	public BasFreezereason setTrack(org.tylproject.db.public_.udt.pojos.Track track) {
		this.track = track;
		return this;
	}
}
