/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BasLanguage implements java.io.Serializable {

	private static final long serialVersionUID = 1747352605;

	private java.lang.String                          idBasLanguage;
	private java.lang.Boolean                         active;
	private java.lang.String                          flag;
	private java.lang.String                          name;
	private java.lang.Boolean                         canceled;
	private java.lang.Integer                         version;
	private org.tylproject.db.public_.udt.pojos.Track track;

	public BasLanguage() {}

	public BasLanguage(
		java.lang.String                          idBasLanguage,
		java.lang.Boolean                         active,
		java.lang.String                          flag,
		java.lang.String                          name,
		java.lang.Boolean                         canceled,
		java.lang.Integer                         version,
		org.tylproject.db.public_.udt.pojos.Track track
	) {
		this.idBasLanguage = idBasLanguage;
		this.active = active;
		this.flag = flag;
		this.name = name;
		this.canceled = canceled;
		this.version = version;
		this.track = track;
	}

	public java.lang.String getIdBasLanguage() {
		return this.idBasLanguage;
	}

	public BasLanguage setIdBasLanguage(java.lang.String idBasLanguage) {
		this.idBasLanguage = idBasLanguage;
		return this;
	}

	public java.lang.Boolean getActive() {
		return this.active;
	}

	public BasLanguage setActive(java.lang.Boolean active) {
		this.active = active;
		return this;
	}

	public java.lang.String getFlag() {
		return this.flag;
	}

	public BasLanguage setFlag(java.lang.String flag) {
		this.flag = flag;
		return this;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public BasLanguage setName(java.lang.String name) {
		this.name = name;
		return this;
	}

	public java.lang.Boolean getCanceled() {
		return this.canceled;
	}

	public BasLanguage setCanceled(java.lang.Boolean canceled) {
		this.canceled = canceled;
		return this;
	}

	public java.lang.Integer getVersion() {
		return this.version;
	}

	public BasLanguage setVersion(java.lang.Integer version) {
		this.version = version;
		return this;
	}

	public org.tylproject.db.public_.udt.pojos.Track getTrack() {
		return this.track;
	}

	public BasLanguage setTrack(org.tylproject.db.public_.udt.pojos.Track track) {
		this.track = track;
		return this;
	}
}
