/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BasLanguage implements java.io.Serializable {

	private static final long serialVersionUID = -1363189314;

	private java.lang.String   idBasLanguage;
	private java.lang.String   flag;
	private java.lang.String   name;
	private java.sql.Timestamp createdOn;
	private java.lang.String   createdBy;
	private java.sql.Timestamp updatedOn;
	private java.lang.String   updatedBy;
	private java.lang.Boolean  canceled;
	private java.lang.Integer  version;
	private java.lang.Boolean  active;

	public BasLanguage() {}

	public BasLanguage(
		java.lang.String   idBasLanguage,
		java.lang.String   flag,
		java.lang.String   name,
		java.sql.Timestamp createdOn,
		java.lang.String   createdBy,
		java.sql.Timestamp updatedOn,
		java.lang.String   updatedBy,
		java.lang.Boolean  canceled,
		java.lang.Integer  version,
		java.lang.Boolean  active
	) {
		this.idBasLanguage = idBasLanguage;
		this.flag = flag;
		this.name = name;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.updatedOn = updatedOn;
		this.updatedBy = updatedBy;
		this.canceled = canceled;
		this.version = version;
		this.active = active;
	}

	public java.lang.String getIdBasLanguage() {
		return this.idBasLanguage;
	}

	public BasLanguage setIdBasLanguage(java.lang.String idBasLanguage) {
		this.idBasLanguage = idBasLanguage;
		return this;
	}

	public java.lang.String getFlag() {
		return this.flag;
	}

	public BasLanguage setFlag(java.lang.String flag) {
		this.flag = flag;
		return this;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public BasLanguage setName(java.lang.String name) {
		this.name = name;
		return this;
	}

	public java.sql.Timestamp getCreatedOn() {
		return this.createdOn;
	}

	public BasLanguage setCreatedOn(java.sql.Timestamp createdOn) {
		this.createdOn = createdOn;
		return this;
	}

	public java.lang.String getCreatedBy() {
		return this.createdBy;
	}

	public BasLanguage setCreatedBy(java.lang.String createdBy) {
		this.createdBy = createdBy;
		return this;
	}

	public java.sql.Timestamp getUpdatedOn() {
		return this.updatedOn;
	}

	public BasLanguage setUpdatedOn(java.sql.Timestamp updatedOn) {
		this.updatedOn = updatedOn;
		return this;
	}

	public java.lang.String getUpdatedBy() {
		return this.updatedBy;
	}

	public BasLanguage setUpdatedBy(java.lang.String updatedBy) {
		this.updatedBy = updatedBy;
		return this;
	}

	public java.lang.Boolean getCanceled() {
		return this.canceled;
	}

	public BasLanguage setCanceled(java.lang.Boolean canceled) {
		this.canceled = canceled;
		return this;
	}

	public java.lang.Integer getVersion() {
		return this.version;
	}

	public BasLanguage setVersion(java.lang.Integer version) {
		this.version = version;
		return this;
	}

	public java.lang.Boolean getActive() {
		return this.active;
	}

	public BasLanguage setActive(java.lang.Boolean active) {
		this.active = active;
		return this;
	}
}
