/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExcExchangerate implements java.io.Serializable {

	private static final long serialVersionUID = -451092207;

	private java.lang.Integer idExcExchangerate;

	public ExcExchangerate() {}

	public ExcExchangerate(
		java.lang.Integer idExcExchangerate
	) {
		this.idExcExchangerate = idExcExchangerate;
	}

	public java.lang.Integer getIdExcExchangerate() {
		return this.idExcExchangerate;
	}

	public ExcExchangerate setIdExcExchangerate(java.lang.Integer idExcExchangerate) {
		this.idExcExchangerate = idExcExchangerate;
		return this;
	}
}
