/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExcForeigncurrency implements java.io.Serializable {

	private static final long serialVersionUID = -1124325987;

	private java.lang.String idExcForeigncurrency;

	public ExcForeigncurrency() {}

	public ExcForeigncurrency(
		java.lang.String idExcForeigncurrency
	) {
		this.idExcForeigncurrency = idExcForeigncurrency;
	}

	public java.lang.String getIdExcForeigncurrency() {
		return this.idExcForeigncurrency;
	}

	public ExcForeigncurrency setIdExcForeigncurrency(java.lang.String idExcForeigncurrency) {
		this.idExcForeigncurrency = idExcForeigncurrency;
		return this;
	}
}
