/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.udt;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Track extends org.jooq.impl.UDTImpl<org.tylproject.db.public_.udt.records.TrackRecord> {

	private static final long serialVersionUID = -1075427774;

	/**
	 * The singleton instance of <code>public.track</code>
	 */
	public static final org.tylproject.db.public_.udt.Track TRACK = new org.tylproject.db.public_.udt.Track();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.tylproject.db.public_.udt.records.TrackRecord> getRecordType() {
		return org.tylproject.db.public_.udt.records.TrackRecord.class;
	}

	/**
	 * The attribute <code>public.track.created_on</code>.
	 */
	public static final org.jooq.UDTField<org.tylproject.db.public_.udt.records.TrackRecord, java.sql.Timestamp> CREATED_ON = createField("created_on", org.jooq.impl.SQLDataType.TIMESTAMP, TRACK);

	/**
	 * The attribute <code>public.track.created_by</code>.
	 */
	public static final org.jooq.UDTField<org.tylproject.db.public_.udt.records.TrackRecord, java.lang.String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(128), TRACK);

	/**
	 * The attribute <code>public.track.updated_on</code>.
	 */
	public static final org.jooq.UDTField<org.tylproject.db.public_.udt.records.TrackRecord, java.sql.Timestamp> UPDATED_ON = createField("updated_on", org.jooq.impl.SQLDataType.TIMESTAMP, TRACK);

	/**
	 * The attribute <code>public.track.updated_by</code>.
	 */
	public static final org.jooq.UDTField<org.tylproject.db.public_.udt.records.TrackRecord, java.lang.String> UPDATED_BY = createField("updated_by", org.jooq.impl.SQLDataType.VARCHAR.length(128), TRACK);

	/**
	 * No further instances allowed
	 */
	private Track() {
		super("track", org.tylproject.db.public_.Public.PUBLIC);

		// Initialise data type
		getDataType();
	}
}
