/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutUserroleCompanyRecord extends org.jooq.impl.UpdatableRecordImpl<org.tylproject.db.public_.tables.records.AutUserroleCompanyRecord> implements org.jooq.Record9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -1479273985;

	/**
	 * Setter for <code>public.aut_userrole_company.id_aut_userrole_company</code>.
	 */
	public AutUserroleCompanyRecord setIdAutUserroleCompany(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.aut_userrole_company.id_aut_userrole_company</code>.
	 */
	public java.lang.Integer getIdAutUserroleCompany() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.aut_userrole_company.id_aut_user</code>.
	 */
	public AutUserroleCompanyRecord setIdAutUser(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.aut_userrole_company.id_aut_user</code>.
	 */
	public java.lang.String getIdAutUser() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.aut_userrole_company.id_aut_userrole</code>.
	 */
	public AutUserroleCompanyRecord setIdAutUserrole(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.aut_userrole_company.id_aut_userrole</code>.
	 */
	public java.lang.String getIdAutUserrole() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.aut_userrole_company.id_aut_company</code>.
	 */
	public AutUserroleCompanyRecord setIdAutCompany(java.lang.String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.aut_userrole_company.id_aut_company</code>.
	 */
	public java.lang.String getIdAutCompany() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.aut_userrole_company.created_on</code>.
	 */
	public AutUserroleCompanyRecord setCreatedOn(java.sql.Timestamp value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.aut_userrole_company.created_on</code>.
	 */
	public java.sql.Timestamp getCreatedOn() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>public.aut_userrole_company.created_by</code>.
	 */
	public AutUserroleCompanyRecord setCreatedBy(java.lang.String value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>public.aut_userrole_company.created_by</code>.
	 */
	public java.lang.String getCreatedBy() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.aut_userrole_company.updated_on</code>.
	 */
	public AutUserroleCompanyRecord setUpdatedOn(java.sql.Timestamp value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>public.aut_userrole_company.updated_on</code>.
	 */
	public java.sql.Timestamp getUpdatedOn() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>public.aut_userrole_company.updated_by</code>.
	 */
	public AutUserroleCompanyRecord setUpdatedBy(java.lang.String value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>public.aut_userrole_company.updated_by</code>.
	 */
	public java.lang.String getUpdatedBy() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>public.aut_userrole_company.version</code>.
	 */
	public AutUserroleCompanyRecord setVersion(java.lang.Integer value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>public.aut_userrole_company.version</code>.
	 */
	public java.lang.Integer getVersion() {
		return (java.lang.Integer) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.ID_AUT_USERROLE_COMPANY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.ID_AUT_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.ID_AUT_USERROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.ID_AUT_COMPANY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.CREATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.CREATED_BY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.UPDATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.UPDATED_BY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdAutUserroleCompany();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getIdAutUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getIdAutUserrole();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getIdAutCompany();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getCreatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getCreatedBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getUpdatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getUpdatedBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleCompanyRecord value1(java.lang.Integer value) {
		setIdAutUserroleCompany(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleCompanyRecord value2(java.lang.String value) {
		setIdAutUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleCompanyRecord value3(java.lang.String value) {
		setIdAutUserrole(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleCompanyRecord value4(java.lang.String value) {
		setIdAutCompany(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleCompanyRecord value5(java.sql.Timestamp value) {
		setCreatedOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleCompanyRecord value6(java.lang.String value) {
		setCreatedBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleCompanyRecord value7(java.sql.Timestamp value) {
		setUpdatedOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleCompanyRecord value8(java.lang.String value) {
		setUpdatedBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleCompanyRecord value9(java.lang.Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleCompanyRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.sql.Timestamp value5, java.lang.String value6, java.sql.Timestamp value7, java.lang.String value8, java.lang.Integer value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AutUserroleCompanyRecord
	 */
	public AutUserroleCompanyRecord() {
		super(org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY);
	}

	/**
	 * Create a detached, initialised AutUserroleCompanyRecord
	 */
	public AutUserroleCompanyRecord(java.lang.Integer idAutUserroleCompany, java.lang.String idAutUser, java.lang.String idAutUserrole, java.lang.String idAutCompany, java.sql.Timestamp createdOn, java.lang.String createdBy, java.sql.Timestamp updatedOn, java.lang.String updatedBy, java.lang.Integer version) {
		super(org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY);

		setValue(0, idAutUserroleCompany);
		setValue(1, idAutUser);
		setValue(2, idAutUserrole);
		setValue(3, idAutCompany);
		setValue(4, createdOn);
		setValue(5, createdBy);
		setValue(6, updatedOn);
		setValue(7, updatedBy);
		setValue(8, version);
	}
}
