/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutUserroleRecord extends org.jooq.impl.UpdatableRecordImpl<org.tylproject.db.public_.tables.records.AutUserroleRecord> implements org.jooq.Record4<java.lang.String, java.lang.Boolean, java.lang.Integer, org.tylproject.db.public_.udt.records.TrackRecord> {

	private static final long serialVersionUID = 58494629;

	/**
	 * Setter for <code>public.aut_userrole.id_aut_userrole</code>.
	 */
	public AutUserroleRecord setIdAutUserrole(java.lang.String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.aut_userrole.id_aut_userrole</code>.
	 */
	public java.lang.String getIdAutUserrole() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.aut_userrole.canceled</code>.
	 */
	public AutUserroleRecord setCanceled(java.lang.Boolean value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.aut_userrole.canceled</code>.
	 */
	public java.lang.Boolean getCanceled() {
		return (java.lang.Boolean) getValue(1);
	}

	/**
	 * Setter for <code>public.aut_userrole.version</code>.
	 */
	public AutUserroleRecord setVersion(java.lang.Integer value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.aut_userrole.version</code>.
	 */
	public java.lang.Integer getVersion() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.aut_userrole.track</code>.
	 */
	public AutUserroleRecord setTrack(org.tylproject.db.public_.udt.records.TrackRecord value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.aut_userrole.track</code>.
	 */
	public org.tylproject.db.public_.udt.records.TrackRecord getTrack() {
		return (org.tylproject.db.public_.udt.records.TrackRecord) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.Boolean, java.lang.Integer, org.tylproject.db.public_.udt.records.TrackRecord> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.Boolean, java.lang.Integer, org.tylproject.db.public_.udt.records.TrackRecord> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return org.tylproject.db.public_.tables.AutUserrole.AUT_USERROLE.ID_AUT_USERROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field2() {
		return org.tylproject.db.public_.tables.AutUserrole.AUT_USERROLE.CANCELED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return org.tylproject.db.public_.tables.AutUserrole.AUT_USERROLE.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.tylproject.db.public_.udt.records.TrackRecord> field4() {
		return org.tylproject.db.public_.tables.AutUserrole.AUT_USERROLE.TRACK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getIdAutUserrole();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value2() {
		return getCanceled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.tylproject.db.public_.udt.records.TrackRecord value4() {
		return getTrack();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleRecord value1(java.lang.String value) {
		setIdAutUserrole(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleRecord value2(java.lang.Boolean value) {
		setCanceled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleRecord value3(java.lang.Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleRecord value4(org.tylproject.db.public_.udt.records.TrackRecord value) {
		setTrack(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleRecord values(java.lang.String value1, java.lang.Boolean value2, java.lang.Integer value3, org.tylproject.db.public_.udt.records.TrackRecord value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AutUserroleRecord
	 */
	public AutUserroleRecord() {
		super(org.tylproject.db.public_.tables.AutUserrole.AUT_USERROLE);
	}

	/**
	 * Create a detached, initialised AutUserroleRecord
	 */
	public AutUserroleRecord(java.lang.String idAutUserrole, java.lang.Boolean canceled, java.lang.Integer version, org.tylproject.db.public_.udt.records.TrackRecord track) {
		super(org.tylproject.db.public_.tables.AutUserrole.AUT_USERROLE);

		setValue(0, idAutUserrole);
		setValue(1, canceled);
		setValue(2, version);
		setValue(3, track);
	}
}
