/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutUserroleCompanyRecord extends org.jooq.impl.UpdatableRecordImpl<org.tylproject.db.public_.tables.records.AutUserroleCompanyRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, org.tylproject.db.public_.udt.records.TrackRecord> {

	private static final long serialVersionUID = 316887443;

	/**
	 * Setter for <code>public.aut_userrole_company.id_aut_userrole_company</code>.
	 */
	public AutUserroleCompanyRecord setIdAutUserroleCompany(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.aut_userrole_company.id_aut_userrole_company</code>.
	 */
	public java.lang.Integer getIdAutUserroleCompany() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.aut_userrole_company.id_aut_user</code>.
	 */
	public AutUserroleCompanyRecord setIdAutUser(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.aut_userrole_company.id_aut_user</code>.
	 */
	public java.lang.String getIdAutUser() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.aut_userrole_company.id_aut_userrole</code>.
	 */
	public AutUserroleCompanyRecord setIdAutUserrole(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.aut_userrole_company.id_aut_userrole</code>.
	 */
	public java.lang.String getIdAutUserrole() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.aut_userrole_company.id_aut_company</code>.
	 */
	public AutUserroleCompanyRecord setIdAutCompany(java.lang.String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.aut_userrole_company.id_aut_company</code>.
	 */
	public java.lang.String getIdAutCompany() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.aut_userrole_company.version</code>.
	 */
	public AutUserroleCompanyRecord setVersion(java.lang.Integer value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.aut_userrole_company.version</code>.
	 */
	public java.lang.Integer getVersion() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>public.aut_userrole_company.track</code>.
	 */
	public AutUserroleCompanyRecord setTrack(org.tylproject.db.public_.udt.records.TrackRecord value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>public.aut_userrole_company.track</code>.
	 */
	public org.tylproject.db.public_.udt.records.TrackRecord getTrack() {
		return (org.tylproject.db.public_.udt.records.TrackRecord) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, org.tylproject.db.public_.udt.records.TrackRecord> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, org.tylproject.db.public_.udt.records.TrackRecord> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.ID_AUT_USERROLE_COMPANY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.ID_AUT_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.ID_AUT_USERROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.ID_AUT_COMPANY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.tylproject.db.public_.udt.records.TrackRecord> field6() {
		return org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.TRACK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdAutUserroleCompany();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getIdAutUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getIdAutUserrole();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getIdAutCompany();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.tylproject.db.public_.udt.records.TrackRecord value6() {
		return getTrack();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleCompanyRecord value1(java.lang.Integer value) {
		setIdAutUserroleCompany(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleCompanyRecord value2(java.lang.String value) {
		setIdAutUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleCompanyRecord value3(java.lang.String value) {
		setIdAutUserrole(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleCompanyRecord value4(java.lang.String value) {
		setIdAutCompany(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleCompanyRecord value5(java.lang.Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleCompanyRecord value6(org.tylproject.db.public_.udt.records.TrackRecord value) {
		setTrack(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutUserroleCompanyRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.Integer value5, org.tylproject.db.public_.udt.records.TrackRecord value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AutUserroleCompanyRecord
	 */
	public AutUserroleCompanyRecord() {
		super(org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY);
	}

	/**
	 * Create a detached, initialised AutUserroleCompanyRecord
	 */
	public AutUserroleCompanyRecord(java.lang.Integer idAutUserroleCompany, java.lang.String idAutUser, java.lang.String idAutUserrole, java.lang.String idAutCompany, java.lang.Integer version, org.tylproject.db.public_.udt.records.TrackRecord track) {
		super(org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY);

		setValue(0, idAutUserroleCompany);
		setValue(1, idAutUser);
		setValue(2, idAutUserrole);
		setValue(3, idAutCompany);
		setValue(4, version);
		setValue(5, track);
	}
}
