/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BasCountryRecord extends org.jooq.impl.UpdatableRecordImpl<org.tylproject.db.public_.tables.records.BasCountryRecord> implements org.jooq.Record10<java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Boolean, java.lang.Integer> {

	private static final long serialVersionUID = -1095143032;

	/**
	 * Setter for <code>public.bas_country.id_bas_country</code>.
	 */
	public BasCountryRecord setIdBasCountry(java.lang.String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_country.id_bas_country</code>.
	 */
	public java.lang.String getIdBasCountry() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.bas_country.official_name</code>.
	 */
	public BasCountryRecord setOfficialName(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_country.official_name</code>.
	 */
	public java.lang.String getOfficialName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.bas_country.two_chars_code</code>.
	 */
	public BasCountryRecord setTwoCharsCode(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_country.two_chars_code</code>.
	 */
	public java.lang.String getTwoCharsCode() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.bas_country.numeric_code</code>.
	 */
	public BasCountryRecord setNumericCode(java.lang.Integer value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_country.numeric_code</code>.
	 */
	public java.lang.Integer getNumericCode() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.bas_country.created_on</code>.
	 */
	public BasCountryRecord setCreatedOn(java.sql.Timestamp value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_country.created_on</code>.
	 */
	public java.sql.Timestamp getCreatedOn() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>public.bas_country.created_by</code>.
	 */
	public BasCountryRecord setCreatedBy(java.lang.String value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_country.created_by</code>.
	 */
	public java.lang.String getCreatedBy() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.bas_country.updated_on</code>.
	 */
	public BasCountryRecord setUpdatedOn(java.sql.Timestamp value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_country.updated_on</code>.
	 */
	public java.sql.Timestamp getUpdatedOn() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>public.bas_country.updated_by</code>.
	 */
	public BasCountryRecord setUpdatedBy(java.lang.String value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_country.updated_by</code>.
	 */
	public java.lang.String getUpdatedBy() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>public.bas_country.canceled</code>.
	 */
	public BasCountryRecord setCanceled(java.lang.Boolean value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_country.canceled</code>.
	 */
	public java.lang.Boolean getCanceled() {
		return (java.lang.Boolean) getValue(8);
	}

	/**
	 * Setter for <code>public.bas_country.version</code>.
	 */
	public BasCountryRecord setVersion(java.lang.Integer value) {
		setValue(9, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_country.version</code>.
	 */
	public java.lang.Integer getVersion() {
		return (java.lang.Integer) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Boolean, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Boolean, java.lang.Integer> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return org.tylproject.db.public_.tables.BasCountry.BAS_COUNTRY.ID_BAS_COUNTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.tylproject.db.public_.tables.BasCountry.BAS_COUNTRY.OFFICIAL_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.tylproject.db.public_.tables.BasCountry.BAS_COUNTRY.TWO_CHARS_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return org.tylproject.db.public_.tables.BasCountry.BAS_COUNTRY.NUMERIC_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return org.tylproject.db.public_.tables.BasCountry.BAS_COUNTRY.CREATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return org.tylproject.db.public_.tables.BasCountry.BAS_COUNTRY.CREATED_BY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return org.tylproject.db.public_.tables.BasCountry.BAS_COUNTRY.UPDATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return org.tylproject.db.public_.tables.BasCountry.BAS_COUNTRY.UPDATED_BY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field9() {
		return org.tylproject.db.public_.tables.BasCountry.BAS_COUNTRY.CANCELED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return org.tylproject.db.public_.tables.BasCountry.BAS_COUNTRY.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getIdBasCountry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getOfficialName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getTwoCharsCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getNumericCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getCreatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getCreatedBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getUpdatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getUpdatedBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value9() {
		return getCanceled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasCountryRecord value1(java.lang.String value) {
		setIdBasCountry(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasCountryRecord value2(java.lang.String value) {
		setOfficialName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasCountryRecord value3(java.lang.String value) {
		setTwoCharsCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasCountryRecord value4(java.lang.Integer value) {
		setNumericCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasCountryRecord value5(java.sql.Timestamp value) {
		setCreatedOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasCountryRecord value6(java.lang.String value) {
		setCreatedBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasCountryRecord value7(java.sql.Timestamp value) {
		setUpdatedOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasCountryRecord value8(java.lang.String value) {
		setUpdatedBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasCountryRecord value9(java.lang.Boolean value) {
		setCanceled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasCountryRecord value10(java.lang.Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasCountryRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.Integer value4, java.sql.Timestamp value5, java.lang.String value6, java.sql.Timestamp value7, java.lang.String value8, java.lang.Boolean value9, java.lang.Integer value10) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BasCountryRecord
	 */
	public BasCountryRecord() {
		super(org.tylproject.db.public_.tables.BasCountry.BAS_COUNTRY);
	}

	/**
	 * Create a detached, initialised BasCountryRecord
	 */
	public BasCountryRecord(java.lang.String idBasCountry, java.lang.String officialName, java.lang.String twoCharsCode, java.lang.Integer numericCode, java.sql.Timestamp createdOn, java.lang.String createdBy, java.sql.Timestamp updatedOn, java.lang.String updatedBy, java.lang.Boolean canceled, java.lang.Integer version) {
		super(org.tylproject.db.public_.tables.BasCountry.BAS_COUNTRY);

		setValue(0, idBasCountry);
		setValue(1, officialName);
		setValue(2, twoCharsCode);
		setValue(3, numericCode);
		setValue(4, createdOn);
		setValue(5, createdBy);
		setValue(6, updatedOn);
		setValue(7, updatedBy);
		setValue(8, canceled);
		setValue(9, version);
	}
}
