/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BasFreezereasonRecord extends org.jooq.impl.UpdatableRecordImpl<org.tylproject.db.public_.tables.records.BasFreezereasonRecord> implements org.jooq.Record6<java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Integer, org.tylproject.db.public_.udt.records.TrackRecord> {

	private static final long serialVersionUID = 1215886257;

	/**
	 * Setter for <code>public.bas_freezereason.id_freezereason</code>.
	 */
	public BasFreezereasonRecord setIdFreezereason(java.lang.String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_freezereason.id_freezereason</code>.
	 */
	public java.lang.String getIdFreezereason() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.bas_freezereason.discriminator</code>.
	 */
	public BasFreezereasonRecord setDiscriminator(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_freezereason.discriminator</code>.
	 */
	public java.lang.String getDiscriminator() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.bas_freezereason.description</code>.
	 */
	public BasFreezereasonRecord setDescription(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_freezereason.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.bas_freezereason.canceled</code>.
	 */
	public BasFreezereasonRecord setCanceled(java.lang.Boolean value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_freezereason.canceled</code>.
	 */
	public java.lang.Boolean getCanceled() {
		return (java.lang.Boolean) getValue(3);
	}

	/**
	 * Setter for <code>public.bas_freezereason.version</code>.
	 */
	public BasFreezereasonRecord setVersion(java.lang.Integer value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_freezereason.version</code>.
	 */
	public java.lang.Integer getVersion() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>public.bas_freezereason.track</code>.
	 */
	public BasFreezereasonRecord setTrack(org.tylproject.db.public_.udt.records.TrackRecord value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_freezereason.track</code>.
	 */
	public org.tylproject.db.public_.udt.records.TrackRecord getTrack() {
		return (org.tylproject.db.public_.udt.records.TrackRecord) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Integer, org.tylproject.db.public_.udt.records.TrackRecord> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Integer, org.tylproject.db.public_.udt.records.TrackRecord> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return org.tylproject.db.public_.tables.BasFreezereason.BAS_FREEZEREASON.ID_FREEZEREASON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.tylproject.db.public_.tables.BasFreezereason.BAS_FREEZEREASON.DISCRIMINATOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.tylproject.db.public_.tables.BasFreezereason.BAS_FREEZEREASON.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field4() {
		return org.tylproject.db.public_.tables.BasFreezereason.BAS_FREEZEREASON.CANCELED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return org.tylproject.db.public_.tables.BasFreezereason.BAS_FREEZEREASON.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.tylproject.db.public_.udt.records.TrackRecord> field6() {
		return org.tylproject.db.public_.tables.BasFreezereason.BAS_FREEZEREASON.TRACK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getIdFreezereason();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDiscriminator();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value4() {
		return getCanceled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.tylproject.db.public_.udt.records.TrackRecord value6() {
		return getTrack();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasFreezereasonRecord value1(java.lang.String value) {
		setIdFreezereason(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasFreezereasonRecord value2(java.lang.String value) {
		setDiscriminator(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasFreezereasonRecord value3(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasFreezereasonRecord value4(java.lang.Boolean value) {
		setCanceled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasFreezereasonRecord value5(java.lang.Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasFreezereasonRecord value6(org.tylproject.db.public_.udt.records.TrackRecord value) {
		setTrack(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasFreezereasonRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.Boolean value4, java.lang.Integer value5, org.tylproject.db.public_.udt.records.TrackRecord value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BasFreezereasonRecord
	 */
	public BasFreezereasonRecord() {
		super(org.tylproject.db.public_.tables.BasFreezereason.BAS_FREEZEREASON);
	}

	/**
	 * Create a detached, initialised BasFreezereasonRecord
	 */
	public BasFreezereasonRecord(java.lang.String idFreezereason, java.lang.String discriminator, java.lang.String description, java.lang.Boolean canceled, java.lang.Integer version, org.tylproject.db.public_.udt.records.TrackRecord track) {
		super(org.tylproject.db.public_.tables.BasFreezereason.BAS_FREEZEREASON);

		setValue(0, idFreezereason);
		setValue(1, discriminator);
		setValue(2, description);
		setValue(3, canceled);
		setValue(4, version);
		setValue(5, track);
	}
}
