/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BasLanguageRecord extends org.jooq.impl.UpdatableRecordImpl<org.tylproject.db.public_.tables.records.BasLanguageRecord> implements org.jooq.Record7<java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Integer, org.tylproject.db.public_.udt.records.TrackRecord> {

	private static final long serialVersionUID = -883309477;

	/**
	 * Setter for <code>public.bas_language.id_bas_language</code>.
	 */
	public BasLanguageRecord setIdBasLanguage(java.lang.String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_language.id_bas_language</code>.
	 */
	public java.lang.String getIdBasLanguage() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.bas_language.active</code>.
	 */
	public BasLanguageRecord setActive(java.lang.Boolean value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_language.active</code>.
	 */
	public java.lang.Boolean getActive() {
		return (java.lang.Boolean) getValue(1);
	}

	/**
	 * Setter for <code>public.bas_language.flag</code>.
	 */
	public BasLanguageRecord setFlag(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_language.flag</code>.
	 */
	public java.lang.String getFlag() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.bas_language.name</code>.
	 */
	public BasLanguageRecord setName(java.lang.String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_language.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.bas_language.canceled</code>.
	 */
	public BasLanguageRecord setCanceled(java.lang.Boolean value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_language.canceled</code>.
	 */
	public java.lang.Boolean getCanceled() {
		return (java.lang.Boolean) getValue(4);
	}

	/**
	 * Setter for <code>public.bas_language.version</code>.
	 */
	public BasLanguageRecord setVersion(java.lang.Integer value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_language.version</code>.
	 */
	public java.lang.Integer getVersion() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>public.bas_language.track</code>.
	 */
	public BasLanguageRecord setTrack(org.tylproject.db.public_.udt.records.TrackRecord value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_language.track</code>.
	 */
	public org.tylproject.db.public_.udt.records.TrackRecord getTrack() {
		return (org.tylproject.db.public_.udt.records.TrackRecord) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Integer, org.tylproject.db.public_.udt.records.TrackRecord> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Integer, org.tylproject.db.public_.udt.records.TrackRecord> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.ID_BAS_LANGUAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field2() {
		return org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.ACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.FLAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field5() {
		return org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.CANCELED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.tylproject.db.public_.udt.records.TrackRecord> field7() {
		return org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.TRACK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getIdBasLanguage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value2() {
		return getActive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getFlag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value5() {
		return getCanceled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.tylproject.db.public_.udt.records.TrackRecord value7() {
		return getTrack();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasLanguageRecord value1(java.lang.String value) {
		setIdBasLanguage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasLanguageRecord value2(java.lang.Boolean value) {
		setActive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasLanguageRecord value3(java.lang.String value) {
		setFlag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasLanguageRecord value4(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasLanguageRecord value5(java.lang.Boolean value) {
		setCanceled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasLanguageRecord value6(java.lang.Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasLanguageRecord value7(org.tylproject.db.public_.udt.records.TrackRecord value) {
		setTrack(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasLanguageRecord values(java.lang.String value1, java.lang.Boolean value2, java.lang.String value3, java.lang.String value4, java.lang.Boolean value5, java.lang.Integer value6, org.tylproject.db.public_.udt.records.TrackRecord value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BasLanguageRecord
	 */
	public BasLanguageRecord() {
		super(org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE);
	}

	/**
	 * Create a detached, initialised BasLanguageRecord
	 */
	public BasLanguageRecord(java.lang.String idBasLanguage, java.lang.Boolean active, java.lang.String flag, java.lang.String name, java.lang.Boolean canceled, java.lang.Integer version, org.tylproject.db.public_.udt.records.TrackRecord track) {
		super(org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE);

		setValue(0, idBasLanguage);
		setValue(1, active);
		setValue(2, flag);
		setValue(3, name);
		setValue(4, canceled);
		setValue(5, version);
		setValue(6, track);
	}
}
