/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BasLanguageRecord extends org.jooq.impl.UpdatableRecordImpl<org.tylproject.db.public_.tables.records.BasLanguageRecord> implements org.jooq.Record10<java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Boolean, java.lang.Integer, java.lang.Boolean> {

	private static final long serialVersionUID = -455715325;

	/**
	 * Setter for <code>public.bas_language.id_bas_language</code>.
	 */
	public BasLanguageRecord setIdBasLanguage(java.lang.String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_language.id_bas_language</code>.
	 */
	public java.lang.String getIdBasLanguage() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.bas_language.flag</code>.
	 */
	public BasLanguageRecord setFlag(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_language.flag</code>.
	 */
	public java.lang.String getFlag() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.bas_language.name</code>.
	 */
	public BasLanguageRecord setName(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_language.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.bas_language.created_on</code>.
	 */
	public BasLanguageRecord setCreatedOn(java.sql.Timestamp value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_language.created_on</code>.
	 */
	public java.sql.Timestamp getCreatedOn() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>public.bas_language.created_by</code>.
	 */
	public BasLanguageRecord setCreatedBy(java.lang.String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_language.created_by</code>.
	 */
	public java.lang.String getCreatedBy() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.bas_language.updated_on</code>.
	 */
	public BasLanguageRecord setUpdatedOn(java.sql.Timestamp value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_language.updated_on</code>.
	 */
	public java.sql.Timestamp getUpdatedOn() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>public.bas_language.updated_by</code>.
	 */
	public BasLanguageRecord setUpdatedBy(java.lang.String value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_language.updated_by</code>.
	 */
	public java.lang.String getUpdatedBy() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.bas_language.canceled</code>.
	 */
	public BasLanguageRecord setCanceled(java.lang.Boolean value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_language.canceled</code>.
	 */
	public java.lang.Boolean getCanceled() {
		return (java.lang.Boolean) getValue(7);
	}

	/**
	 * Setter for <code>public.bas_language.version</code>.
	 */
	public BasLanguageRecord setVersion(java.lang.Integer value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_language.version</code>.
	 */
	public java.lang.Integer getVersion() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>public.bas_language.active</code>.
	 */
	public BasLanguageRecord setActive(java.lang.Boolean value) {
		setValue(9, value);
		return this;
	}

	/**
	 * Getter for <code>public.bas_language.active</code>.
	 */
	public java.lang.Boolean getActive() {
		return (java.lang.Boolean) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Boolean, java.lang.Integer, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Boolean, java.lang.Integer, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.ID_BAS_LANGUAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.FLAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.CREATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.CREATED_BY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.UPDATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.UPDATED_BY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field8() {
		return org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.CANCELED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field10() {
		return org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.ACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getIdBasLanguage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getFlag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getCreatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getCreatedBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getUpdatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getUpdatedBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value8() {
		return getCanceled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value10() {
		return getActive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasLanguageRecord value1(java.lang.String value) {
		setIdBasLanguage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasLanguageRecord value2(java.lang.String value) {
		setFlag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasLanguageRecord value3(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasLanguageRecord value4(java.sql.Timestamp value) {
		setCreatedOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasLanguageRecord value5(java.lang.String value) {
		setCreatedBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasLanguageRecord value6(java.sql.Timestamp value) {
		setUpdatedOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasLanguageRecord value7(java.lang.String value) {
		setUpdatedBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasLanguageRecord value8(java.lang.Boolean value) {
		setCanceled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasLanguageRecord value9(java.lang.Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasLanguageRecord value10(java.lang.Boolean value) {
		setActive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BasLanguageRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.sql.Timestamp value4, java.lang.String value5, java.sql.Timestamp value6, java.lang.String value7, java.lang.Boolean value8, java.lang.Integer value9, java.lang.Boolean value10) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BasLanguageRecord
	 */
	public BasLanguageRecord() {
		super(org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE);
	}

	/**
	 * Create a detached, initialised BasLanguageRecord
	 */
	public BasLanguageRecord(java.lang.String idBasLanguage, java.lang.String flag, java.lang.String name, java.sql.Timestamp createdOn, java.lang.String createdBy, java.sql.Timestamp updatedOn, java.lang.String updatedBy, java.lang.Boolean canceled, java.lang.Integer version, java.lang.Boolean active) {
		super(org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE);

		setValue(0, idBasLanguage);
		setValue(1, flag);
		setValue(2, name);
		setValue(3, createdOn);
		setValue(4, createdBy);
		setValue(5, updatedOn);
		setValue(6, updatedBy);
		setValue(7, canceled);
		setValue(8, version);
		setValue(9, active);
	}
}
