/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExcExchangerateRecord extends org.jooq.impl.UpdatableRecordImpl<org.tylproject.db.public_.tables.records.ExcExchangerateRecord> implements org.jooq.Record1<java.lang.Integer> {

	private static final long serialVersionUID = -1351614956;

	/**
	 * Setter for <code>public.exc_exchangerate.id_exc_exchangerate</code>.
	 */
	public ExcExchangerateRecord setIdExcExchangerate(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.exc_exchangerate.id_exc_exchangerate</code>.
	 */
	public java.lang.Integer getIdExcExchangerate() {
		return (java.lang.Integer) getValue(0);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record1 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.Integer> fieldsRow() {
		return (org.jooq.Row1) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.Integer> valuesRow() {
		return (org.jooq.Row1) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.tylproject.db.public_.tables.ExcExchangerate.EXC_EXCHANGERATE.ID_EXC_EXCHANGERATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdExcExchangerate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExcExchangerateRecord value1(java.lang.Integer value) {
		setIdExcExchangerate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExcExchangerateRecord values(java.lang.Integer value1) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ExcExchangerateRecord
	 */
	public ExcExchangerateRecord() {
		super(org.tylproject.db.public_.tables.ExcExchangerate.EXC_EXCHANGERATE);
	}

	/**
	 * Create a detached, initialised ExcExchangerateRecord
	 */
	public ExcExchangerateRecord(java.lang.Integer idExcExchangerate) {
		super(org.tylproject.db.public_.tables.ExcExchangerate.EXC_EXCHANGERATE);

		setValue(0, idExcExchangerate);
	}
}
