/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExcForeigncurrencyRecord extends org.jooq.impl.UpdatableRecordImpl<org.tylproject.db.public_.tables.records.ExcForeigncurrencyRecord> implements org.jooq.Record6<java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Integer, org.tylproject.db.public_.udt.records.TrackRecord> {

	private static final long serialVersionUID = -770932843;

	/**
	 * Setter for <code>public.exc_foreigncurrency.id_exc_foreigncurrency</code>.
	 */
	public ExcForeigncurrencyRecord setIdExcForeigncurrency(java.lang.String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.exc_foreigncurrency.id_exc_foreigncurrency</code>.
	 */
	public java.lang.String getIdExcForeigncurrency() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.exc_foreigncurrency.symbol</code>.
	 */
	public ExcForeigncurrencyRecord setSymbol(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.exc_foreigncurrency.symbol</code>.
	 */
	public java.lang.String getSymbol() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.exc_foreigncurrency.name</code>.
	 */
	public ExcForeigncurrencyRecord setName(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.exc_foreigncurrency.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.exc_foreigncurrency.canceled</code>.
	 */
	public ExcForeigncurrencyRecord setCanceled(java.lang.Boolean value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.exc_foreigncurrency.canceled</code>.
	 */
	public java.lang.Boolean getCanceled() {
		return (java.lang.Boolean) getValue(3);
	}

	/**
	 * Setter for <code>public.exc_foreigncurrency.version</code>.
	 */
	public ExcForeigncurrencyRecord setVersion(java.lang.Integer value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.exc_foreigncurrency.version</code>.
	 */
	public java.lang.Integer getVersion() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>public.exc_foreigncurrency.track</code>.
	 */
	public ExcForeigncurrencyRecord setTrack(org.tylproject.db.public_.udt.records.TrackRecord value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>public.exc_foreigncurrency.track</code>.
	 */
	public org.tylproject.db.public_.udt.records.TrackRecord getTrack() {
		return (org.tylproject.db.public_.udt.records.TrackRecord) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Integer, org.tylproject.db.public_.udt.records.TrackRecord> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Integer, org.tylproject.db.public_.udt.records.TrackRecord> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return org.tylproject.db.public_.tables.ExcForeigncurrency.EXC_FOREIGNCURRENCY.ID_EXC_FOREIGNCURRENCY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.tylproject.db.public_.tables.ExcForeigncurrency.EXC_FOREIGNCURRENCY.SYMBOL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.tylproject.db.public_.tables.ExcForeigncurrency.EXC_FOREIGNCURRENCY.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field4() {
		return org.tylproject.db.public_.tables.ExcForeigncurrency.EXC_FOREIGNCURRENCY.CANCELED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return org.tylproject.db.public_.tables.ExcForeigncurrency.EXC_FOREIGNCURRENCY.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.tylproject.db.public_.udt.records.TrackRecord> field6() {
		return org.tylproject.db.public_.tables.ExcForeigncurrency.EXC_FOREIGNCURRENCY.TRACK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getIdExcForeigncurrency();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getSymbol();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value4() {
		return getCanceled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.tylproject.db.public_.udt.records.TrackRecord value6() {
		return getTrack();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExcForeigncurrencyRecord value1(java.lang.String value) {
		setIdExcForeigncurrency(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExcForeigncurrencyRecord value2(java.lang.String value) {
		setSymbol(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExcForeigncurrencyRecord value3(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExcForeigncurrencyRecord value4(java.lang.Boolean value) {
		setCanceled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExcForeigncurrencyRecord value5(java.lang.Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExcForeigncurrencyRecord value6(org.tylproject.db.public_.udt.records.TrackRecord value) {
		setTrack(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExcForeigncurrencyRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.Boolean value4, java.lang.Integer value5, org.tylproject.db.public_.udt.records.TrackRecord value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ExcForeigncurrencyRecord
	 */
	public ExcForeigncurrencyRecord() {
		super(org.tylproject.db.public_.tables.ExcForeigncurrency.EXC_FOREIGNCURRENCY);
	}

	/**
	 * Create a detached, initialised ExcForeigncurrencyRecord
	 */
	public ExcForeigncurrencyRecord(java.lang.String idExcForeigncurrency, java.lang.String symbol, java.lang.String name, java.lang.Boolean canceled, java.lang.Integer version, org.tylproject.db.public_.udt.records.TrackRecord track) {
		super(org.tylproject.db.public_.tables.ExcForeigncurrency.EXC_FOREIGNCURRENCY);

		setValue(0, idExcForeigncurrency);
		setValue(1, symbol);
		setValue(2, name);
		setValue(3, canceled);
		setValue(4, version);
		setValue(5, track);
	}
}
