/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TodosRecord extends org.jooq.impl.UpdatableRecordImpl<org.tylproject.db.public_.tables.records.TodosRecord> implements org.jooq.Record5<java.lang.Integer, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.String> {

	private static final long serialVersionUID = 1728468127;

	/**
	 * Setter for <code>public.todos.id</code>.
	 */
	public TodosRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.todos.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.todos.creation_time</code>.
	 */
	public TodosRecord setCreationTime(java.sql.Timestamp value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.todos.creation_time</code>.
	 */
	public java.sql.Timestamp getCreationTime() {
		return (java.sql.Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>public.todos.description</code>.
	 */
	public TodosRecord setDescription(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.todos.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.todos.modification_time</code>.
	 */
	public TodosRecord setModificationTime(java.sql.Timestamp value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.todos.modification_time</code>.
	 */
	public java.sql.Timestamp getModificationTime() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>public.todos.title</code>.
	 */
	public TodosRecord setTitle(java.lang.String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.todos.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.tylproject.db.public_.tables.Todos.TODOS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field2() {
		return org.tylproject.db.public_.tables.Todos.TODOS.CREATION_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.tylproject.db.public_.tables.Todos.TODOS.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return org.tylproject.db.public_.tables.Todos.TODOS.MODIFICATION_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return org.tylproject.db.public_.tables.Todos.TODOS.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value2() {
		return getCreationTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getModificationTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TodosRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TodosRecord value2(java.sql.Timestamp value) {
		setCreationTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TodosRecord value3(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TodosRecord value4(java.sql.Timestamp value) {
		setModificationTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TodosRecord value5(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TodosRecord values(java.lang.Integer value1, java.sql.Timestamp value2, java.lang.String value3, java.sql.Timestamp value4, java.lang.String value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TodosRecord
	 */
	public TodosRecord() {
		super(org.tylproject.db.public_.tables.Todos.TODOS);
	}

	/**
	 * Create a detached, initialised TodosRecord
	 */
	public TodosRecord(java.lang.Integer id, java.sql.Timestamp creationTime, java.lang.String description, java.sql.Timestamp modificationTime, java.lang.String title) {
		super(org.tylproject.db.public_.tables.Todos.TODOS);

		setValue(0, id);
		setValue(1, creationTime);
		setValue(2, description);
		setValue(3, modificationTime);
		setValue(4, title);
	}
}
