/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.tyl;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tyl extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1388922406;

	/**
	 * The singleton instance of <code>tyl</code>
	 */
	public static final Tyl TYL = new Tyl();

	/**
	 * No further instances allowed
	 */
	private Tyl() {
		super("tyl");
	}
}
