/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutCompany extends org.jooq.impl.TableImpl<org.tylproject.db.public_.tables.records.AutCompanyRecord> {

	private static final long serialVersionUID = 55694854;

	/**
	 * The singleton instance of <code>public.aut_company</code>
	 */
	public static final org.tylproject.db.public_.tables.AutCompany AUT_COMPANY = new org.tylproject.db.public_.tables.AutCompany();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.tylproject.db.public_.tables.records.AutCompanyRecord> getRecordType() {
		return org.tylproject.db.public_.tables.records.AutCompanyRecord.class;
	}

	/**
	 * The column <code>public.aut_company.id_aut_company</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.AutCompanyRecord, java.lang.String> ID_AUT_COMPANY = createField("id_aut_company", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>public.aut_company.name</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.AutCompanyRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>public.aut_company.id_par_party</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.AutCompanyRecord, java.lang.Integer> ID_PAR_PARTY = createField("id_par_party", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.aut_company.canceled</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.AutCompanyRecord, java.lang.Boolean> CANCELED = createField("canceled", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * The column <code>public.aut_company.version</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.AutCompanyRecord, java.lang.Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>public.aut_company.track</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.AutCompanyRecord, org.tylproject.db.public_.udt.records.TrackRecord> TRACK = createField("track", org.tylproject.db.public_.udt.Track.TRACK.getDataType(), this, "");

	/**
	 * Create a <code>public.aut_company</code> table reference
	 */
	public AutCompany() {
		this("aut_company", null);
	}

	/**
	 * Create an aliased <code>public.aut_company</code> table reference
	 */
	public AutCompany(java.lang.String alias) {
		this(alias, org.tylproject.db.public_.tables.AutCompany.AUT_COMPANY);
	}

	private AutCompany(java.lang.String alias, org.jooq.Table<org.tylproject.db.public_.tables.records.AutCompanyRecord> aliased) {
		this(alias, aliased, null);
	}

	private AutCompany(java.lang.String alias, org.jooq.Table<org.tylproject.db.public_.tables.records.AutCompanyRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.tylproject.db.public_.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.AutCompanyRecord> getPrimaryKey() {
		return org.tylproject.db.public_.Keys.AUT_COMPANY_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.AutCompanyRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.AutCompanyRecord>>asList(org.tylproject.db.public_.Keys.AUT_COMPANY_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.TableField<org.tylproject.db.public_.tables.records.AutCompanyRecord, java.lang.Integer> getRecordVersion() {
		return org.tylproject.db.public_.tables.AutCompany.AUT_COMPANY.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.tylproject.db.public_.tables.AutCompany as(java.lang.String alias) {
		return new org.tylproject.db.public_.tables.AutCompany(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.tylproject.db.public_.tables.AutCompany rename(java.lang.String name) {
		return new org.tylproject.db.public_.tables.AutCompany(name, null);
	}
}
