/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutUserrole extends org.jooq.impl.TableImpl<org.tylproject.db.public_.tables.records.AutUserroleRecord> {

	private static final long serialVersionUID = -1373316873;

	/**
	 * The singleton instance of <code>public.aut_userrole</code>
	 */
	public static final org.tylproject.db.public_.tables.AutUserrole AUT_USERROLE = new org.tylproject.db.public_.tables.AutUserrole();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.tylproject.db.public_.tables.records.AutUserroleRecord> getRecordType() {
		return org.tylproject.db.public_.tables.records.AutUserroleRecord.class;
	}

	/**
	 * The column <code>public.aut_userrole.id_aut_userrole</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.AutUserroleRecord, java.lang.String> ID_AUT_USERROLE = createField("id_aut_userrole", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>public.aut_userrole.canceled</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.AutUserroleRecord, java.lang.Boolean> CANCELED = createField("canceled", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * The column <code>public.aut_userrole.version</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.AutUserroleRecord, java.lang.Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.aut_userrole.track</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.AutUserroleRecord, org.tylproject.db.public_.udt.records.TrackRecord> TRACK = createField("track", org.tylproject.db.public_.udt.Track.TRACK.getDataType(), this, "");

	/**
	 * Create a <code>public.aut_userrole</code> table reference
	 */
	public AutUserrole() {
		this("aut_userrole", null);
	}

	/**
	 * Create an aliased <code>public.aut_userrole</code> table reference
	 */
	public AutUserrole(java.lang.String alias) {
		this(alias, org.tylproject.db.public_.tables.AutUserrole.AUT_USERROLE);
	}

	private AutUserrole(java.lang.String alias, org.jooq.Table<org.tylproject.db.public_.tables.records.AutUserroleRecord> aliased) {
		this(alias, aliased, null);
	}

	private AutUserrole(java.lang.String alias, org.jooq.Table<org.tylproject.db.public_.tables.records.AutUserroleRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.tylproject.db.public_.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.AutUserroleRecord> getPrimaryKey() {
		return org.tylproject.db.public_.Keys.AUT_USERROLE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.AutUserroleRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.AutUserroleRecord>>asList(org.tylproject.db.public_.Keys.AUT_USERROLE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.TableField<org.tylproject.db.public_.tables.records.AutUserroleRecord, java.lang.Integer> getRecordVersion() {
		return org.tylproject.db.public_.tables.AutUserrole.AUT_USERROLE.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.tylproject.db.public_.tables.AutUserrole as(java.lang.String alias) {
		return new org.tylproject.db.public_.tables.AutUserrole(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.tylproject.db.public_.tables.AutUserrole rename(java.lang.String name) {
		return new org.tylproject.db.public_.tables.AutUserrole(name, null);
	}
}
