/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BasCountry extends org.jooq.impl.TableImpl<org.tylproject.db.public_.tables.records.BasCountryRecord> {

	private static final long serialVersionUID = 1577714688;

	/**
	 * The singleton instance of <code>public.bas_country</code>
	 */
	public static final org.tylproject.db.public_.tables.BasCountry BAS_COUNTRY = new org.tylproject.db.public_.tables.BasCountry();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.tylproject.db.public_.tables.records.BasCountryRecord> getRecordType() {
		return org.tylproject.db.public_.tables.records.BasCountryRecord.class;
	}

	/**
	 * The column <code>public.bas_country.id_bas_country</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasCountryRecord, java.lang.String> ID_BAS_COUNTRY = createField("id_bas_country", org.jooq.impl.SQLDataType.VARCHAR.length(3).nullable(false), this, "");

	/**
	 * The column <code>public.bas_country.official_name</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasCountryRecord, java.lang.String> OFFICIAL_NAME = createField("official_name", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>public.bas_country.two_chars_code</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasCountryRecord, java.lang.String> TWO_CHARS_CODE = createField("two_chars_code", org.jooq.impl.SQLDataType.CHAR.length(2), this, "");

	/**
	 * The column <code>public.bas_country.numeric_code</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasCountryRecord, java.lang.Integer> NUMERIC_CODE = createField("numeric_code", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.bas_country.created_on</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasCountryRecord, java.sql.Timestamp> CREATED_ON = createField("created_on", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>public.bas_country.created_by</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasCountryRecord, java.lang.String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(1), this, "");

	/**
	 * The column <code>public.bas_country.updated_on</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasCountryRecord, java.sql.Timestamp> UPDATED_ON = createField("updated_on", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>public.bas_country.updated_by</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasCountryRecord, java.lang.String> UPDATED_BY = createField("updated_by", org.jooq.impl.SQLDataType.VARCHAR.length(1), this, "");

	/**
	 * The column <code>public.bas_country.canceled</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasCountryRecord, java.lang.Boolean> CANCELED = createField("canceled", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * The column <code>public.bas_country.version</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasCountryRecord, java.lang.Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.bas_country</code> table reference
	 */
	public BasCountry() {
		this("bas_country", null);
	}

	/**
	 * Create an aliased <code>public.bas_country</code> table reference
	 */
	public BasCountry(java.lang.String alias) {
		this(alias, org.tylproject.db.public_.tables.BasCountry.BAS_COUNTRY);
	}

	private BasCountry(java.lang.String alias, org.jooq.Table<org.tylproject.db.public_.tables.records.BasCountryRecord> aliased) {
		this(alias, aliased, null);
	}

	private BasCountry(java.lang.String alias, org.jooq.Table<org.tylproject.db.public_.tables.records.BasCountryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.tylproject.db.public_.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.BasCountryRecord> getPrimaryKey() {
		return org.tylproject.db.public_.Keys.BAS_COUNTRY_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.BasCountryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.BasCountryRecord>>asList(org.tylproject.db.public_.Keys.BAS_COUNTRY_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.TableField<org.tylproject.db.public_.tables.records.BasCountryRecord, java.lang.Integer> getRecordVersion() {
		return org.tylproject.db.public_.tables.BasCountry.BAS_COUNTRY.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.tylproject.db.public_.tables.BasCountry as(java.lang.String alias) {
		return new org.tylproject.db.public_.tables.BasCountry(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.tylproject.db.public_.tables.BasCountry rename(java.lang.String name) {
		return new org.tylproject.db.public_.tables.BasCountry(name, null);
	}
}
