/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BasDistrict extends org.jooq.impl.TableImpl<org.tylproject.db.public_.tables.records.BasDistrictRecord> {

	private static final long serialVersionUID = 908000880;

	/**
	 * The singleton instance of <code>public.bas_district</code>
	 */
	public static final org.tylproject.db.public_.tables.BasDistrict BAS_DISTRICT = new org.tylproject.db.public_.tables.BasDistrict();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.tylproject.db.public_.tables.records.BasDistrictRecord> getRecordType() {
		return org.tylproject.db.public_.tables.records.BasDistrictRecord.class;
	}

	/**
	 * The column <code>public.bas_district.id_bas_district</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasDistrictRecord, java.lang.Integer> ID_BAS_DISTRICT = createField("id_bas_district", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.bas_district.id_bas_country</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasDistrictRecord, java.lang.String> ID_BAS_COUNTRY = createField("id_bas_country", org.jooq.impl.SQLDataType.VARCHAR.length(3), this, "");

	/**
	 * The column <code>public.bas_district.district</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasDistrictRecord, java.lang.String> DISTRICT = createField("district", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>public.bas_district.city_name</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasDistrictRecord, java.lang.String> CITY_NAME = createField("city_name", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>public.bas_district.postal_code</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasDistrictRecord, java.lang.String> POSTAL_CODE = createField("postal_code", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "");

	/**
	 * The column <code>public.bas_district.created_on</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasDistrictRecord, java.sql.Timestamp> CREATED_ON = createField("created_on", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>public.bas_district.created_by</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasDistrictRecord, java.lang.String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(1), this, "");

	/**
	 * The column <code>public.bas_district.updated_on</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasDistrictRecord, java.sql.Timestamp> UPDATED_ON = createField("updated_on", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>public.bas_district.updated_by</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasDistrictRecord, java.lang.String> UPDATED_BY = createField("updated_by", org.jooq.impl.SQLDataType.VARCHAR.length(1), this, "");

	/**
	 * The column <code>public.bas_district.canceled</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasDistrictRecord, java.lang.Boolean> CANCELED = createField("canceled", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * The column <code>public.bas_district.version</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasDistrictRecord, java.lang.Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * Create a <code>public.bas_district</code> table reference
	 */
	public BasDistrict() {
		this("bas_district", null);
	}

	/**
	 * Create an aliased <code>public.bas_district</code> table reference
	 */
	public BasDistrict(java.lang.String alias) {
		this(alias, org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT);
	}

	private BasDistrict(java.lang.String alias, org.jooq.Table<org.tylproject.db.public_.tables.records.BasDistrictRecord> aliased) {
		this(alias, aliased, null);
	}

	private BasDistrict(java.lang.String alias, org.jooq.Table<org.tylproject.db.public_.tables.records.BasDistrictRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.tylproject.db.public_.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.tylproject.db.public_.tables.records.BasDistrictRecord, java.lang.Integer> getIdentity() {
		return org.tylproject.db.public_.Keys.IDENTITY_BAS_DISTRICT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.BasDistrictRecord> getPrimaryKey() {
		return org.tylproject.db.public_.Keys.BAS_DISTRICT_BAS_COUNTY_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.BasDistrictRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.BasDistrictRecord>>asList(org.tylproject.db.public_.Keys.BAS_DISTRICT_BAS_COUNTY_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.tylproject.db.public_.tables.records.BasDistrictRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.tylproject.db.public_.tables.records.BasDistrictRecord, ?>>asList(org.tylproject.db.public_.Keys.BAS_DISTRICT__BAS_DISTRICT_FK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.TableField<org.tylproject.db.public_.tables.records.BasDistrictRecord, java.lang.Integer> getRecordVersion() {
		return org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.tylproject.db.public_.tables.BasDistrict as(java.lang.String alias) {
		return new org.tylproject.db.public_.tables.BasDistrict(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.tylproject.db.public_.tables.BasDistrict rename(java.lang.String name) {
		return new org.tylproject.db.public_.tables.BasDistrict(name, null);
	}
}
