/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BasLanguage extends org.jooq.impl.TableImpl<org.tylproject.db.public_.tables.records.BasLanguageRecord> {

	private static final long serialVersionUID = -2042686459;

	/**
	 * The singleton instance of <code>public.bas_language</code>
	 */
	public static final org.tylproject.db.public_.tables.BasLanguage BAS_LANGUAGE = new org.tylproject.db.public_.tables.BasLanguage();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.tylproject.db.public_.tables.records.BasLanguageRecord> getRecordType() {
		return org.tylproject.db.public_.tables.records.BasLanguageRecord.class;
	}

	/**
	 * The column <code>public.bas_language.id_bas_language</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasLanguageRecord, java.lang.String> ID_BAS_LANGUAGE = createField("id_bas_language", org.jooq.impl.SQLDataType.VARCHAR.length(5).nullable(false), this, "");

	/**
	 * The column <code>public.bas_language.active</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasLanguageRecord, java.lang.Boolean> ACTIVE = createField("active", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

	/**
	 * The column <code>public.bas_language.flag</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasLanguageRecord, java.lang.String> FLAG = createField("flag", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>public.bas_language.name</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasLanguageRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>public.bas_language.canceled</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasLanguageRecord, java.lang.Boolean> CANCELED = createField("canceled", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * The column <code>public.bas_language.version</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasLanguageRecord, java.lang.Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.bas_language.track</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.BasLanguageRecord, org.tylproject.db.public_.udt.records.TrackRecord> TRACK = createField("track", org.tylproject.db.public_.udt.Track.TRACK.getDataType(), this, "");

	/**
	 * Create a <code>public.bas_language</code> table reference
	 */
	public BasLanguage() {
		this("bas_language", null);
	}

	/**
	 * Create an aliased <code>public.bas_language</code> table reference
	 */
	public BasLanguage(java.lang.String alias) {
		this(alias, org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE);
	}

	private BasLanguage(java.lang.String alias, org.jooq.Table<org.tylproject.db.public_.tables.records.BasLanguageRecord> aliased) {
		this(alias, aliased, null);
	}

	private BasLanguage(java.lang.String alias, org.jooq.Table<org.tylproject.db.public_.tables.records.BasLanguageRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.tylproject.db.public_.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.BasLanguageRecord> getPrimaryKey() {
		return org.tylproject.db.public_.Keys.BAS_LANGUAGE_BAS_FOREIGNLANGUAGE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.BasLanguageRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.BasLanguageRecord>>asList(org.tylproject.db.public_.Keys.BAS_LANGUAGE_BAS_FOREIGNLANGUAGE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.TableField<org.tylproject.db.public_.tables.records.BasLanguageRecord, java.lang.Integer> getRecordVersion() {
		return org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.tylproject.db.public_.tables.BasLanguage as(java.lang.String alias) {
		return new org.tylproject.db.public_.tables.BasLanguage(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.tylproject.db.public_.tables.BasLanguage rename(java.lang.String name) {
		return new org.tylproject.db.public_.tables.BasLanguage(name, null);
	}
}
