/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExcExchangerate extends org.jooq.impl.TableImpl<org.tylproject.db.public_.tables.records.ExcExchangerateRecord> {

	private static final long serialVersionUID = 1431437562;

	/**
	 * The singleton instance of <code>public.exc_exchangerate</code>
	 */
	public static final org.tylproject.db.public_.tables.ExcExchangerate EXC_EXCHANGERATE = new org.tylproject.db.public_.tables.ExcExchangerate();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.tylproject.db.public_.tables.records.ExcExchangerateRecord> getRecordType() {
		return org.tylproject.db.public_.tables.records.ExcExchangerateRecord.class;
	}

	/**
	 * The column <code>public.exc_exchangerate.id_exc_exchangerate</code>.
	 */
	public final org.jooq.TableField<org.tylproject.db.public_.tables.records.ExcExchangerateRecord, java.lang.Integer> ID_EXC_EXCHANGERATE = createField("id_exc_exchangerate", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.exc_exchangerate</code> table reference
	 */
	public ExcExchangerate() {
		this("exc_exchangerate", null);
	}

	/**
	 * Create an aliased <code>public.exc_exchangerate</code> table reference
	 */
	public ExcExchangerate(java.lang.String alias) {
		this(alias, org.tylproject.db.public_.tables.ExcExchangerate.EXC_EXCHANGERATE);
	}

	private ExcExchangerate(java.lang.String alias, org.jooq.Table<org.tylproject.db.public_.tables.records.ExcExchangerateRecord> aliased) {
		this(alias, aliased, null);
	}

	private ExcExchangerate(java.lang.String alias, org.jooq.Table<org.tylproject.db.public_.tables.records.ExcExchangerateRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.tylproject.db.public_.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.tylproject.db.public_.tables.records.ExcExchangerateRecord, java.lang.Integer> getIdentity() {
		return org.tylproject.db.public_.Keys.IDENTITY_EXC_EXCHANGERATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.ExcExchangerateRecord> getPrimaryKey() {
		return org.tylproject.db.public_.Keys.EXC_EXCHANGERATE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.ExcExchangerateRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.ExcExchangerateRecord>>asList(org.tylproject.db.public_.Keys.EXC_EXCHANGERATE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.tylproject.db.public_.tables.ExcExchangerate as(java.lang.String alias) {
		return new org.tylproject.db.public_.tables.ExcExchangerate(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.tylproject.db.public_.tables.ExcExchangerate rename(java.lang.String name) {
		return new org.tylproject.db.public_.tables.ExcExchangerate(name, null);
	}
}
