/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_.udt.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Track implements java.io.Serializable {

	private static final long serialVersionUID = -965732417;

	private java.sql.Timestamp createdOn;
	private java.lang.String   createdBy;
	private java.sql.Timestamp updatedOn;
	private java.lang.String   updatedBy;

	public Track() {}

	public Track(
		java.sql.Timestamp createdOn,
		java.lang.String   createdBy,
		java.sql.Timestamp updatedOn,
		java.lang.String   updatedBy
	) {
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.updatedOn = updatedOn;
		this.updatedBy = updatedBy;
	}

	public java.sql.Timestamp getCreatedOn() {
		return this.createdOn;
	}

	public Track setCreatedOn(java.sql.Timestamp createdOn) {
		this.createdOn = createdOn;
		return this;
	}

	public java.lang.String getCreatedBy() {
		return this.createdBy;
	}

	public Track setCreatedBy(java.lang.String createdBy) {
		this.createdBy = createdBy;
		return this;
	}

	public java.sql.Timestamp getUpdatedOn() {
		return this.updatedOn;
	}

	public Track setUpdatedOn(java.sql.Timestamp updatedOn) {
		this.updatedOn = updatedOn;
		return this;
	}

	public java.lang.String getUpdatedBy() {
		return this.updatedBy;
	}

	public Track setUpdatedBy(java.lang.String updatedBy) {
		this.updatedBy = updatedBy;
		return this;
	}
}
