/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<org.tylproject.db.public_.tables.records.AutUserroleCompanyRecord, java.lang.Integer> IDENTITY_AUT_USERROLE_COMPANY = Identities0.IDENTITY_AUT_USERROLE_COMPANY;
	public static final org.jooq.Identity<org.tylproject.db.public_.tables.records.BasDistrictRecord, java.lang.Integer> IDENTITY_BAS_DISTRICT = Identities0.IDENTITY_BAS_DISTRICT;
	public static final org.jooq.Identity<org.tylproject.db.public_.tables.records.ExcExchangerateRecord, java.lang.Integer> IDENTITY_EXC_EXCHANGERATE = Identities0.IDENTITY_EXC_EXCHANGERATE;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.AutCompanyRecord> AUT_COMPANY_PKEY = UniqueKeys0.AUT_COMPANY_PKEY;
	public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.AutUserRecord> AUT_USER_IDX = UniqueKeys0.AUT_USER_IDX;
	public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.AutUserroleRecord> AUT_USERROLE_PKEY = UniqueKeys0.AUT_USERROLE_PKEY;
	public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.AutUserroleCompanyRecord> AUT_USERROLE_COMPANY_AUT_USERCOMPROLE_PKEY = UniqueKeys0.AUT_USERROLE_COMPANY_AUT_USERCOMPROLE_PKEY;
	public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.BasCountryRecord> BAS_COUNTRY_PKEY = UniqueKeys0.BAS_COUNTRY_PKEY;
	public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.BasDistrictRecord> BAS_DISTRICT_BAS_COUNTY_PKEY = UniqueKeys0.BAS_DISTRICT_BAS_COUNTY_PKEY;
	public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.BasFreezereasonRecord> BAS_FREEZEREASON_PKEY = UniqueKeys0.BAS_FREEZEREASON_PKEY;
	public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.BasLanguageRecord> BAS_LANGUAGE_BAS_FOREIGNLANGUAGE_PKEY = UniqueKeys0.BAS_LANGUAGE_BAS_FOREIGNLANGUAGE_PKEY;
	public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.ExcExchangerateRecord> EXC_EXCHANGERATE_PKEY = UniqueKeys0.EXC_EXCHANGERATE_PKEY;
	public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.ExcForeigncurrencyRecord> TABEXC_FOREIGNCURRENCY_PKEY = UniqueKeys0.TABEXC_FOREIGNCURRENCY_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<org.tylproject.db.public_.tables.records.AutUserroleCompanyRecord, org.tylproject.db.public_.tables.records.AutUserRecord> AUT_USERROLE_COMPANY__AUT_USER_FK = ForeignKeys0.AUT_USERROLE_COMPANY__AUT_USER_FK;
	public static final org.jooq.ForeignKey<org.tylproject.db.public_.tables.records.AutUserroleCompanyRecord, org.tylproject.db.public_.tables.records.AutUserroleRecord> AUT_USERROLE_COMPANY__AUT_USERROLE_FK = ForeignKeys0.AUT_USERROLE_COMPANY__AUT_USERROLE_FK;
	public static final org.jooq.ForeignKey<org.tylproject.db.public_.tables.records.AutUserroleCompanyRecord, org.tylproject.db.public_.tables.records.AutCompanyRecord> AUT_USERROLE_COMPANY__AUT_USERROLE_COMPANY_FK = ForeignKeys0.AUT_USERROLE_COMPANY__AUT_USERROLE_COMPANY_FK;
	public static final org.jooq.ForeignKey<org.tylproject.db.public_.tables.records.BasDistrictRecord, org.tylproject.db.public_.tables.records.BasCountryRecord> BAS_DISTRICT__BAS_DISTRICT_FK = ForeignKeys0.BAS_DISTRICT__BAS_DISTRICT_FK;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<org.tylproject.db.public_.tables.records.AutUserroleCompanyRecord, java.lang.Integer> IDENTITY_AUT_USERROLE_COMPANY = createIdentity(org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY, org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.ID_AUT_USERROLE_COMPANY);
		public static org.jooq.Identity<org.tylproject.db.public_.tables.records.BasDistrictRecord, java.lang.Integer> IDENTITY_BAS_DISTRICT = createIdentity(org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT, org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT.ID_BAS_DISTRICT);
		public static org.jooq.Identity<org.tylproject.db.public_.tables.records.ExcExchangerateRecord, java.lang.Integer> IDENTITY_EXC_EXCHANGERATE = createIdentity(org.tylproject.db.public_.tables.ExcExchangerate.EXC_EXCHANGERATE, org.tylproject.db.public_.tables.ExcExchangerate.EXC_EXCHANGERATE.ID_EXC_EXCHANGERATE);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.AutCompanyRecord> AUT_COMPANY_PKEY = createUniqueKey(org.tylproject.db.public_.tables.AutCompany.AUT_COMPANY, org.tylproject.db.public_.tables.AutCompany.AUT_COMPANY.ID_AUT_COMPANY);
		public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.AutUserRecord> AUT_USER_IDX = createUniqueKey(org.tylproject.db.public_.tables.AutUser.AUT_USER, org.tylproject.db.public_.tables.AutUser.AUT_USER.LOGIN);
		public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.AutUserroleRecord> AUT_USERROLE_PKEY = createUniqueKey(org.tylproject.db.public_.tables.AutUserrole.AUT_USERROLE, org.tylproject.db.public_.tables.AutUserrole.AUT_USERROLE.ID_AUT_USERROLE);
		public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.AutUserroleCompanyRecord> AUT_USERROLE_COMPANY_AUT_USERCOMPROLE_PKEY = createUniqueKey(org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY, org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.ID_AUT_USERROLE_COMPANY);
		public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.BasCountryRecord> BAS_COUNTRY_PKEY = createUniqueKey(org.tylproject.db.public_.tables.BasCountry.BAS_COUNTRY, org.tylproject.db.public_.tables.BasCountry.BAS_COUNTRY.ID_BAS_COUNTRY);
		public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.BasDistrictRecord> BAS_DISTRICT_BAS_COUNTY_PKEY = createUniqueKey(org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT, org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT.ID_BAS_DISTRICT);
		public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.BasFreezereasonRecord> BAS_FREEZEREASON_PKEY = createUniqueKey(org.tylproject.db.public_.tables.BasFreezereason.BAS_FREEZEREASON, org.tylproject.db.public_.tables.BasFreezereason.BAS_FREEZEREASON.ID_FREEZEREASON);
		public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.BasLanguageRecord> BAS_LANGUAGE_BAS_FOREIGNLANGUAGE_PKEY = createUniqueKey(org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE, org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE.ID_BAS_LANGUAGE);
		public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.ExcExchangerateRecord> EXC_EXCHANGERATE_PKEY = createUniqueKey(org.tylproject.db.public_.tables.ExcExchangerate.EXC_EXCHANGERATE, org.tylproject.db.public_.tables.ExcExchangerate.EXC_EXCHANGERATE.ID_EXC_EXCHANGERATE);
		public static final org.jooq.UniqueKey<org.tylproject.db.public_.tables.records.ExcForeigncurrencyRecord> TABEXC_FOREIGNCURRENCY_PKEY = createUniqueKey(org.tylproject.db.public_.tables.ExcForeigncurrency.EXC_FOREIGNCURRENCY, org.tylproject.db.public_.tables.ExcForeigncurrency.EXC_FOREIGNCURRENCY.ID_EXC_FOREIGNCURRENCY);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<org.tylproject.db.public_.tables.records.AutUserroleCompanyRecord, org.tylproject.db.public_.tables.records.AutUserRecord> AUT_USERROLE_COMPANY__AUT_USER_FK = createForeignKey(org.tylproject.db.public_.Keys.AUT_USER_IDX, org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY, org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.ID_AUT_USER);
		public static final org.jooq.ForeignKey<org.tylproject.db.public_.tables.records.AutUserroleCompanyRecord, org.tylproject.db.public_.tables.records.AutUserroleRecord> AUT_USERROLE_COMPANY__AUT_USERROLE_FK = createForeignKey(org.tylproject.db.public_.Keys.AUT_USERROLE_PKEY, org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY, org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.ID_AUT_USERROLE);
		public static final org.jooq.ForeignKey<org.tylproject.db.public_.tables.records.AutUserroleCompanyRecord, org.tylproject.db.public_.tables.records.AutCompanyRecord> AUT_USERROLE_COMPANY__AUT_USERROLE_COMPANY_FK = createForeignKey(org.tylproject.db.public_.Keys.AUT_COMPANY_PKEY, org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY, org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY.ID_AUT_COMPANY);
		public static final org.jooq.ForeignKey<org.tylproject.db.public_.tables.records.BasDistrictRecord, org.tylproject.db.public_.tables.records.BasCountryRecord> BAS_DISTRICT__BAS_DISTRICT_FK = createForeignKey(org.tylproject.db.public_.Keys.BAS_COUNTRY_PKEY, org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT, org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT.ID_BAS_COUNTRY);
	}
}
