/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -341291901;

	/**
	 * The singleton instance of <code>public</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("public");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final java.util.List<org.jooq.Sequence<?>> getSequences0() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			org.tylproject.db.public_.Sequences.AUT_USERCOMPROLE_ID_SEQ,
			org.tylproject.db.public_.Sequences.BAS_DISTRICT_ID_SEQ,
			org.tylproject.db.public_.Sequences.EXC_EXCHANGERATE_IDEXC_EXCHANGERATE_SEQ,
			org.tylproject.db.public_.Sequences.EXC_EXCHANGERATE_ID_SEQ);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			org.tylproject.db.public_.tables.AutCompany.AUT_COMPANY,
			org.tylproject.db.public_.tables.AutUser.AUT_USER,
			org.tylproject.db.public_.tables.AutUserrole.AUT_USERROLE,
			org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY,
			org.tylproject.db.public_.tables.BasCountry.BAS_COUNTRY,
			org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT,
			org.tylproject.db.public_.tables.BasFreezereason.BAS_FREEZEREASON,
			org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE,
			org.tylproject.db.public_.tables.ExcExchangerate.EXC_EXCHANGERATE,
			org.tylproject.db.public_.tables.ExcForeigncurrency.EXC_FOREIGNCURRENCY);
	}

	@Override
	public final java.util.List<org.jooq.UDT<?>> getUDTs() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getUDTs0());
		return result;
	}

	private final java.util.List<org.jooq.UDT<?>> getUDTs0() {
		return java.util.Arrays.<org.jooq.UDT<?>>asList(
			org.tylproject.db.public_.udt.Track.TRACK);
	}
}
