/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.aut_company
	 */
	public static final org.tylproject.db.public_.tables.AutCompany AUT_COMPANY = org.tylproject.db.public_.tables.AutCompany.AUT_COMPANY;

	/**
	 * The table public.aut_user
	 */
	public static final org.tylproject.db.public_.tables.AutUser AUT_USER = org.tylproject.db.public_.tables.AutUser.AUT_USER;

	/**
	 * The table public.aut_userrole
	 */
	public static final org.tylproject.db.public_.tables.AutUserrole AUT_USERROLE = org.tylproject.db.public_.tables.AutUserrole.AUT_USERROLE;

	/**
	 * The table public.aut_userrole_company
	 */
	public static final org.tylproject.db.public_.tables.AutUserroleCompany AUT_USERROLE_COMPANY = org.tylproject.db.public_.tables.AutUserroleCompany.AUT_USERROLE_COMPANY;

	/**
	 * The table public.bas_country
	 */
	public static final org.tylproject.db.public_.tables.BasCountry BAS_COUNTRY = org.tylproject.db.public_.tables.BasCountry.BAS_COUNTRY;

	/**
	 * The table public.bas_district
	 */
	public static final org.tylproject.db.public_.tables.BasDistrict BAS_DISTRICT = org.tylproject.db.public_.tables.BasDistrict.BAS_DISTRICT;

	/**
	 * The table public.bas_freezereason
	 */
	public static final org.tylproject.db.public_.tables.BasFreezereason BAS_FREEZEREASON = org.tylproject.db.public_.tables.BasFreezereason.BAS_FREEZEREASON;

	/**
	 * The table public.bas_language
	 */
	public static final org.tylproject.db.public_.tables.BasLanguage BAS_LANGUAGE = org.tylproject.db.public_.tables.BasLanguage.BAS_LANGUAGE;

	/**
	 * The table public.exc_exchangerate
	 */
	public static final org.tylproject.db.public_.tables.ExcExchangerate EXC_EXCHANGERATE = org.tylproject.db.public_.tables.ExcExchangerate.EXC_EXCHANGERATE;

	/**
	 * The table public.exc_foreigncurrency
	 */
	public static final org.tylproject.db.public_.tables.ExcForeigncurrency EXC_FOREIGNCURRENCY = org.tylproject.db.public_.tables.ExcForeigncurrency.EXC_FOREIGNCURRENCY;

	/**
	 * The table public.todos
	 */
	public static final org.tylproject.db.public_.tables.Todos TODOS = org.tylproject.db.public_.tables.Todos.TODOS;
}
