/**
 * This class is generated by jOOQ
 */
package org.tylproject.db.public_;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all UDTs in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UDTs {

	/**
	 * The type <code>public.track</code>
	 */
	public static org.tylproject.db.public_.udt.Track TRACK = org.tylproject.db.public_.udt.Track.TRACK;
}
